# -*- coding: utf-8 -*-
"""Part 5 — Incomplete Sentences (Q101-130). 100% 신규 창작."""

part5 = [
 {"no":101,"text":"The city council approved a substantial ------- in funding for public transportation projects.",
  "opts":["increased","increase","increasingly","increasing"],"ans":1,"type":"품사·명사",
  "expl":"관사 a와 형용사 substantial의 수식을 받는 <b>명사</b> 자리 → <b>increase</b>(증가). ‘a substantial increase in funding’.",
  "vocab":[("council","의회"),("funding","자금·지원금")]},
 {"no":102,"text":"Ms. Alvarado ------- the keynote address at next month's technology summit.",
  "opts":["delivered","delivering","will deliver","has delivered"],"ans":2,"type":"동사·시제",
  "expl":"미래 표지 ‘next month’가 있으므로 미래시제 <b>will deliver</b>가 정답.",
  "vocab":[("keynote address","기조연설"),("summit","정상회담·총회")]},
 {"no":103,"text":"All laboratory personnel must wear protective eyewear ------- the entire duration of the experiment.",
  "opts":["among","toward","onto","throughout"],"ans":3,"type":"전치사",
  "expl":"‘~하는 내내’를 뜻하는 <b>throughout</b>(the entire duration)이 정답.",
  "vocab":[("duration","(지속) 기간")]},
 {"no":104,"text":"Under the new manager, the warehouse fills online orders far more ------- than before.",
  "opts":["accurately","accurate","accuracy","accurateness"],"ans":0,"type":"품사·부사",
  "expl":"동사 fills를 수식하고 ‘far more ------- than’ 비교 구조에 들어갈 부사 → <b>accurately</b>."},
 {"no":105,"text":"The architect ------- designed the award-winning museum will lead the new library project.",
  "opts":["whom","whose","who","which"],"ans":2,"type":"관계대명사",
  "expl":"사람 선행사(architect)를 받으며 관계절의 주어 역할을 하는 주격 관계대명사 <b>who</b>."},
 {"no":106,"text":"------- its limited marketing budget, the startup attracted thousands of new subscribers.",
  "opts":["Although","Despite","Even though","Whereas"],"ans":1,"type":"전치사 vs 접속사",
  "expl":"뒤에 명사구(its limited marketing budget)가 오므로 전치사 <b>Despite</b>. 나머지는 접속사라 절이 필요하다.",
  "opt_why":["접속사 — 절 필요","전치사(+명사구) ‘~에도 불구하고’ — 정답","접속사 — 절 필요","접속사 ‘~인 반면’ — 절 필요"]},
 {"no":107,"text":"The finance department will ------- all travel expenses within ten business days of submission.",
  "opts":["remind","recover","refer","reimburse"],"ans":3,"type":"어휘·동사",
  "expl":"‘경비를 <b>환급하다</b>’를 뜻하는 reimburse가 정답.",
  "opt_why":["‘(~에게) 상기시키다’","‘되찾다·회복하다’","‘언급하다’(refer to)","경비를 ‘환급하다’ — 정답"],
  "vocab":[("reimburse","환급하다"),("expense","경비"),("submission","제출")]},
 {"no":108,"text":"The board found the consultant's recommendations both practical and -------.",
  "opts":["persuasive","persuade","persuasively","persuasion"],"ans":0,"type":"품사·형용사",
  "expl":"‘both practical and ~’에서 practical과 병렬되는 형용사 → <b>persuasive</b>(설득력 있는)."},
 {"no":109,"text":"The new safety regulations ------- by the committee before they take effect in January.",
  "opts":["will review","reviewing","will be reviewed","have reviewing"],"ans":2,"type":"동사·태",
  "expl":"규정은 검토‘되는’ 대상이고 ‘by the committee’가 있으므로 미래 수동태 <b>will be reviewed</b>.",
  "vocab":[("regulation","규정"),("take effect","발효되다")]},
 {"no":110,"text":"------- of the applicants has submitted the required documentation by the deadline.",
  "opts":["All","Many","Several","Each"],"ans":3,"type":"수일치·수량",
  "expl":"단수 동사 has와 호응하는 <b>Each</b>(of the applicants)가 정답. All·Many·Several은 복수 동사(have)를 취한다.",
  "vocab":[("applicant","지원자"),("documentation","서류")]},
 {"no":111,"text":"Please submit your quarterly report ------- Friday so that we can review it over the weekend.",
  "opts":["until","by","since","within"],"ans":1,"type":"전치사·시간",
  "expl":"제출이 완료되는 시점 ‘~까지’ → <b>by</b> Friday. until은 상태·동작의 계속에 쓴다."},
 {"no":112,"text":"The merger will require the ------- of several regional offices into a single headquarters.",
  "opts":["consolidate","consolidated","consolidation","consolidates"],"ans":2,"type":"품사·명사",
  "expl":"관사 the 뒤 명사 자리 → <b>consolidation</b>(통합).",
  "vocab":[("merger","합병"),("consolidation","통합"),("headquarters","본사")]},
 {"no":113,"text":"The assembly instructions were so ------- that even new employees completed the setup without assistance.",
  "opts":["straightforward","reluctant","tentative","approximate"],"ans":0,"type":"어휘·형용사",
  "expl":"‘so + 형용사 + that’ 구문. 신입도 도움 없이 마칠 만큼 ‘<b>이해하기 쉬운(straightforward)</b>’.",
  "opt_why":["‘이해하기 쉬운·간단명료한’ — 정답","‘꺼리는’","‘잠정적인·머뭇거리는’","‘대략적인’"],
  "vocab":[("straightforward","이해하기 쉬운"),("assembly","조립")]},
 {"no":114,"text":"Customers visiting the newly ------- store received a complimentary gift on opening day.",
  "opts":["renovate","renovating","renovation","renovated"],"ans":3,"type":"품사·분사",
  "expl":"명사 store를 수식하며 ‘개조된’ 수동 의미를 나타내는 과거분사 <b>renovated</b>.",
  "vocab":[("complimentary","무료의")]},
 {"no":115,"text":"The shipment will be delayed ------- the supplier resolves the issue with its manufacturing line.",
  "opts":["during","until","despite","because of"],"ans":1,"type":"접속사",
  "expl":"뒤에 절(the supplier resolves ~)이 오는 시간 접속사 ‘~할 때까지’ → <b>until</b>. despite·because of·during은 명사(구)를 취한다."},
 {"no":116,"text":"The airline advised passengers to ------- their flight status online before heading to the airport.",
  "opts":["persist","belong","confirm","consent"],"ans":2,"type":"어휘·동사",
  "expl":"‘항공편 상태를 <b>확인하다</b>’ → confirm.",
  "opt_why":["‘지속되다’(persist)","‘속하다’(belong to)","‘확인하다’ — 정답","‘동의하다’(consent to)"]},
 {"no":117,"text":"The organization has ------- expanded its outreach programs over the past five years.",
  "opts":["significantly","signify","significant","significance"],"ans":0,"type":"품사·부사",
  "expl":"동사 expanded를 수식하는 부사 → <b>significantly</b>(상당히).",
  "vocab":[("outreach","(지역) 봉사·확장 활동")]},
 {"no":118,"text":"After the training session, employees are encouraged to familiarize ------- with the updated procedures.",
  "opts":["they","them","their","themselves"],"ans":3,"type":"대명사·재귀",
  "expl":"‘familiarize <b>oneself</b> with(~에 익숙해지다)’ 구조. 주어 employees와 동일하므로 재귀대명사 themselves."},
 {"no":119,"text":"The consultant's fee is determined ------- the complexity of each project.",
  "opts":["according","by","into","among"],"ans":1,"type":"전치사",
  "expl":"‘~에 의해 결정되다’ → determined <b>by</b>. according은 to와, into·among은 의미상 부적합.",
  "vocab":[("complexity","복잡성")]},
 {"no":120,"text":"The new policy was implemented in ------- to growing concerns about data privacy.",
  "opts":["contrast","exchange","response","addition"],"ans":2,"type":"어휘·명사(관용)",
  "expl":"‘in <b>response</b> to(~에 대응하여)’가 정답. in contrast to(대조), in exchange for, in addition to(게다가)와 구별.",
  "opt_why":["in contrast to ‘~와 대조적으로’","in exchange for ‘~ 대신’","in response to ‘~에 대응하여’ — 정답","in addition to ‘~에 더하여’"]},
 {"no":121,"text":"To remain competitive, the firm must ------- its production process and reduce costs.",
  "opts":["streamline","streamlined","streamlining","streamlines"],"ans":0,"type":"동사·형태",
  "expl":"조동사 must 뒤에는 동사원형이 오므로 <b>streamline</b>(간소화하다).",
  "vocab":[("streamline","간소화하다"),("competitive","경쟁력 있는")]},
 {"no":122,"text":"Of all the proposals submitted, the one from the Denver office was by far the -------.",
  "opts":["detailed","more detailed","detailing","most detailed"],"ans":3,"type":"비교·최상급",
  "expl":"‘Of all ~’과 ‘by far the’가 있으므로 최상급 <b>most detailed</b>가 정답."},
 {"no":123,"text":"The venue is easily ------- by public transportation, making it ideal for large conferences.",
  "opts":["available","accessible","probable","eligible"],"ans":1,"type":"어휘·형용사",
  "expl":"‘대중교통으로 쉽게 <b>접근 가능한</b>’ → accessible.",
  "opt_why":["‘이용 가능한’(교통수단과 결합 어색)","‘접근 가능한’(accessible by) — 정답","‘있음직한’","‘자격이 있는’(eligible for)"],
  "vocab":[("venue","(행사) 장소")]},
 {"no":124,"text":"The research team collaborated ------- several universities to complete the climate study.",
  "opts":["among","between","with","toward"],"ans":2,"type":"전치사",
  "expl":"‘collaborate <b>with</b>(~와 협력하다)’ 구조."},
 {"no":125,"text":"All ------- for the workshop must be submitted to the human resources department by Friday.",
  "opts":["registrations","register","registered","registering"],"ans":0,"type":"품사·명사",
  "expl":"‘All + 복수명사’ 구조 → <b>registrations</b>(신청서). ‘All registrations must be submitted’."},
 {"no":126,"text":"The renovated lobby features not only a modern reception desk ------- also a comfortable waiting area.",
  "opts":["and","or","nor","but"],"ans":3,"type":"상관접속사",
  "expl":"‘not only A <b>but</b> also B(A뿐 아니라 B도)’ 상관접속사."},
 {"no":127,"text":"Sales representatives are expected to ------- closely to the company's code of conduct at all times.",
  "opts":["respond","adhere","belong","refer"],"ans":1,"type":"어휘·동사",
  "expl":"‘code of conduct(행동 강령)’와 어울려 ‘~을 <b>준수하다</b>’ → adhere (to).",
  "opt_why":["‘반응하다’(respond to)","‘준수하다’(adhere to) — 정답","‘속하다’(belong to)","‘언급하다’(refer to)"],
  "vocab":[("adhere to","준수하다"),("code of conduct","행동 강령")]},
 {"no":128,"text":"The committee described the volunteers' efforts as truly ------- and worthy of recognition.",
  "opts":["inspire","inspired","inspiring","inspiration"],"ans":2,"type":"품사·분사",
  "expl":"노력이 감동을 ‘주는’ 능동 의미이므로 현재분사 <b>inspiring</b>(감동적인). inspired(감동을 받은)는 감정을 느끼는 대상에 쓴다.",
  "vocab":[("worthy of","~할 가치가 있는"),("recognition","인정")]},
 {"no":129,"text":"The keynote speaker's flight was delayed, so the organizers rearranged the schedule -------.",
  "opts":["accordingly","accordance","accordant","according"],"ans":0,"type":"품사·부사",
  "expl":"동사 rearranged를 수식하는 부사 → <b>accordingly</b>(그에 따라). accordance는 명사(in accordance with), according은 according to로 쓴다."},
 {"no":130,"text":"The manufacturer offers a ------- warranty that covers all parts and labor for three years.",
  "opts":["considerate","confident","conscious","comprehensive"],"ans":3,"type":"어휘·형용사",
  "expl":"부품·인건비를 모두 포함하는 ‘<b>포괄적인(comprehensive)</b> 보증’.",
  "opt_why":["‘사려 깊은’","‘자신 있는’","‘의식하는’","‘포괄적인’ — 정답"],
  "vocab":[("warranty","보증"),("comprehensive","포괄적인"),("labor","인건비")]},
]
