# -*- coding: utf-8 -*-
"""
[서아 PT] Part 5 100문제 몰아풀기 (2탄) — 최서아.
원본에 정답이 없어 Claude가 직접 풀이·검산한 정답(selfkey=True).
text의 '▢' 가 빈칸 위치.
"""

seoa100 = [
 {"no":1,"text":"▢ each tour with a guide, visitors are kindly encouraged to share their thoughts or experiences.",
  "opts":["Above","Following","Opposite","Between"],"ans":1,"type":"전치사","selfkey":True,
  "expl":"‘각 투어 <b>후에</b>’를 뜻하는 Following(=after)이 정답."},
 {"no":2,"text":"Hotel shuttle buses depart for the nearby amusement park at thirty-minute ▢.",
  "opts":["divisions","priorities","intervals","intersections"],"ans":2,"type":"어휘·명사","selfkey":True,
  "expl":"‘30분 <b>간격</b>으로’ → at thirty-minute intervals.","vocab":[("interval","간격")]},
 {"no":3,"text":"Feedback from customers ▢ by the marketing department members, as they needed more insights for their newly launched products.",
  "opts":["providing","provided","was provided","will be providing"],"ans":2,"type":"동사·태","selfkey":True,
  "expl":"문장의 본동사가 필요하고 뒤에 ‘by’가 있으므로 <b>수동태 was provided</b>. providing/will be providing은 능동이라 부적합."},
 {"no":4,"text":"Because of a delay in the shipment, some customers might not ▢ our products until Friday morning.",
  "opts":["arrive","prefer","cover","receive"],"ans":3,"type":"어휘·동사","selfkey":True,
  "expl":"‘제품을 <b>받다</b>’ → receive. arrive는 자동사라 목적어를 못 가진다."},
 {"no":5,"text":"The two studies undertaken by the environmental group resulted in ▢ conclusions.",
  "opts":["conflict","conflicts","conflicting","to conflict"],"ans":2,"type":"품사·분사","selfkey":True,
  "expl":"명사 conclusions를 수식하는 분사형용사 <b>conflicting</b>(상충되는)."},
 {"no":6,"text":"Ms. Kim developed from an apprentice into a ▢ successful entrepreneur within just three years.",
  "opts":["financially","financial","finance","finances"],"ans":0,"type":"품사·부사","selfkey":True,
  "expl":"형용사 successful을 수식하는 부사 <b>financially</b>(재정적으로).","vocab":[("apprentice","견습생"),("entrepreneur","기업가")]},
 {"no":7,"text":"▢ job openings will be announced in the employment section of the company’s website.",
  "opts":["Improved","Affordable","Superficial","Internal"],"ans":3,"type":"어휘·형용사","selfkey":True,
  "expl":"‘<b>사내(internal)</b> 채용 공고’가 문맥에 맞는다.","vocab":[("job opening","채용 공고")]},
 {"no":8,"text":"The IT department provided their recommendations, and the legal team shared ▢.",
  "opts":["their","theirs","they","themselves"],"ans":1,"type":"대명사","selfkey":True,
  "expl":"‘their recommendations’를 대신하는 소유대명사 <b>theirs</b>."},
 {"no":9,"text":"Although a specific degree is not required, applicants for management positions should have a broad ▢ of business operations.",
  "opts":["knowledge","construction","distinction","creation"],"ans":0,"type":"어휘·명사","selfkey":True,
  "expl":"‘폭넓은 <b>지식</b>’ → a broad knowledge of."},
 {"no":10,"text":"Riverfront Mall customers who wish to ▢ their products for different items must provide a valid receipt.",
  "opts":["exchange","design","wear","display"],"ans":0,"type":"어휘·동사","selfkey":True,
  "expl":"‘A를 B로 <b>교환</b>하다’ → exchange A for B."},
 {"no":11,"text":"We have implemented efficient problem-solving procedures ▢ there is an issue.",
  "opts":["whenever","quickly","each other","out"],"ans":0,"type":"접속사","selfkey":True,
  "expl":"‘문제가 있을 <b>때마다</b>’ → whenever(+절)."},
 {"no":12,"text":"The rules for all participants in the training program are ▢ and easy to follow.",
  "opts":["fresh","healthy","careful","simple"],"ans":3,"type":"어휘·형용사","selfkey":True,
  "expl":"‘easy to follow’와 병렬되는 ‘<b>간단한(simple)</b>’."},
 {"no":13,"text":"Our team will evaluate the proposals thoroughly ▢ making a final decision.",
  "opts":["also","before","next","whereas"],"ans":1,"type":"전치사","selfkey":True,
  "expl":"‘최종 결정 <b>전에</b>’ → before + 동명사(making)."},
 {"no":14,"text":"According to the marketing director, increasing our online presence is more ▢ than traditional advertising.",
  "opts":["profit","profitable","profits","profiting"],"ans":1,"type":"품사·형용사","selfkey":True,
  "expl":"‘more ~ than’ 비교급에 들어갈 형용사 <b>profitable</b>."},
 {"no":15,"text":"Job applications from candidates around the world are ▢ being evaluated by our HR department.",
  "opts":["currently","exactly","lastly","hardly"],"ans":0,"type":"어휘·부사","selfkey":True,
  "expl":"‘<b>현재</b> 평가되고 있다’ → are currently being evaluated."},
 {"no":16,"text":"The elevators will be out of service ▢ 2 p.m. to 4 p.m. for urgent maintenance.",
  "opts":["since","when","from","over"],"ans":2,"type":"전치사","selfkey":True,
  "expl":"‘from A to B(2시부터 4시까지)’의 <b>from</b>."},
 {"no":17,"text":"The rock band, Electric Pulse, showed a breathtaking performance and received very lengthy ▢ from the enthusiastic crowd.",
  "opts":["applaud","applauded","to applaud","applause"],"ans":3,"type":"품사·명사","selfkey":True,
  "expl":"형용사 lengthy의 수식을 받는 명사 <b>applause</b>(박수).","vocab":[("applause","박수")]},
 {"no":18,"text":"▢ LMN enterprises’ third-quarter revenue saw a sharp increase, customer service evaluations were unexpectedly poor.",
  "opts":["Although","As long as","In case","However"],"ans":0,"type":"접속사","selfkey":True,
  "expl":"‘증가했지만 평가는 나빴다’는 대조 → <b>Although</b>(+절). However는 접속부사라 두 절을 잇지 못한다."},
 {"no":19,"text":"The software ▢ is responsible for creating and maintaining our applications.",
  "opts":["player","character","collector","developer"],"ans":3,"type":"어휘·명사","selfkey":True,
  "expl":"‘앱을 만들고 유지하는’ 주체 → software <b>developer</b>(개발자)."},
 {"no":20,"text":"We will consider all scholarship applications carefully and disregard ▢ that do not meet the eligibility criteria.",
  "opts":["what","any","which","whose"],"ans":1,"type":"대명사","selfkey":True,
  "expl":"‘기준 미달인 <b>것은 무엇이든</b> 무시’ → disregard any that ~.","vocab":[("eligibility","자격")]},
 {"no":21,"text":"Martin Stevens, our HR manager, strongly recommended a colleague of ▢ to streamline the marketing team’s tasks.",
  "opts":["he","him","his","himself"],"ans":2,"type":"대명사·이중소유격","selfkey":True,
  "expl":"‘a + 명사 + of + 소유대명사’ → a colleague of <b>his</b>(그의 동료)."},
 {"no":22,"text":"Nexus Solutions’ new compact electric heaters are more ▢ advanced than the previous models.",
  "opts":["technology","technologies","technologically","technologist"],"ans":2,"type":"품사·부사","selfkey":True,
  "expl":"형용사 advanced를 수식하는 부사 <b>technologically</b>(기술적으로)."},
 {"no":23,"text":"All guests at the Harmony Gala concert hall have been assigned ▢ seats, so we kindly ask that you do not switch seats.",
  "opts":["estimated","qualified","exhausted","designated"],"ans":3,"type":"어휘·형용사","selfkey":True,
  "expl":"‘<b>지정된(designated)</b> 좌석’ — 자리를 바꾸지 말라는 맥락."},
 {"no":24,"text":"All members are ▢ to pay an annual membership fee of $75 by the end of this month.",
  "opts":["calculated","required","considered","achieved"],"ans":1,"type":"어휘·동사","selfkey":True,
  "expl":"‘be <b>required</b> to pay(지불하도록 요구되다)’."},
 {"no":25,"text":"All managers at Elemental Inc. are required to undergo ▢ training to actively implement eco-friendly practices.",
  "opts":["fragile","obscure","apprehensive","mandatory"],"ans":3,"type":"어휘·형용사","selfkey":True,
  "expl":"‘<b>의무(mandatory)</b> 교육을 받다’.","vocab":[("mandatory","의무적인")]},
 {"no":26,"text":"A recent industry study ▢ that employee satisfaction is more important than anticipated.",
  "opts":["has revealed","revealing","reveal","had been revealed"],"ans":0,"type":"동사·시제","selfkey":True,
  "expl":"that절을 목적어로 취하는 능동 동사 <b>has revealed</b>(밝혔다). 수동 had been revealed는 that절을 못 가진다."},
 {"no":27,"text":"Ms. Johnson, the best-selling author, has released her new book, which is popular especially ▢ avid readers.",
  "opts":["along","among","against","above"],"ans":1,"type":"전치사","selfkey":True,
  "expl":"‘열성 독자들 <b>사이에서</b> 인기’ → among.","vocab":[("avid","열렬한")]},
 {"no":28,"text":"▢ hygiene regulations, all surfaces in the kitchen must be regularly sanitized to prevent contamination.",
  "opts":["While","According to","Because","Instead of"],"ans":1,"type":"전치사","selfkey":True,
  "expl":"‘위생 규정에 <b>따라</b>’ → According to(+명사구).","vocab":[("sanitize","소독하다"),("contamination","오염")]},
 {"no":29,"text":"After a lengthy ▢ with key stakeholders, the decision to expand our product line received unanimous approval.",
  "opts":["debate","trial","majority","result"],"ans":0,"type":"어휘·명사","selfkey":True,
  "expl":"‘핵심 이해관계자와의 긴 <b>논의(debate)</b> 후’.","vocab":[("stakeholder","이해관계자")]},
 {"no":30,"text":"The park ranger role at Nature Preserve Services is a great fit for jobseekers with ▢ interest in a typical office job.",
  "opts":["whether","little","few","since"],"ans":1,"type":"수량형용사","selfkey":True,
  "expl":"불가산명사 interest를 수식하는 <b>little</b>(거의 없는). few는 가산명사용."},
 {"no":31,"text":"Unfortunately, we have no choice but ▢ ordering our usual frozen yogurt varieties.",
  "opts":["stopped","will be stopped","stopping","to stop"],"ans":3,"type":"부정사","selfkey":True,
  "expl":"‘have no choice but <b>to</b> + 동사원형(~할 수밖에 없다)’ → to stop."},
 {"no":32,"text":"If you have an interest in space, ▢ you should submit your application form first.",
  "opts":["but","then","along","that"],"ans":1,"type":"부사","selfkey":True,
  "expl":"‘If ~, <b>then</b> ~(그렇다면)’ 호응."},
 {"no":33,"text":"Tickets will remain on sale ▢ the day of the event, but you are advised to purchase one in advance.",
  "opts":["with","by","whether","until"],"ans":3,"type":"전치사·시간","selfkey":True,
  "expl":"판매가 그날까지 ‘계속’되므로 <b>until</b>(~까지 계속). by는 완료 시점."},
 {"no":34,"text":"We appreciate our subscribers, and we hope you are ▢ satisfied with our monthly publication.",
  "opts":["approximately","adversely","consistently","externally"],"ans":2,"type":"어휘·부사","selfkey":True,
  "expl":"‘<b>지속적으로(consistently)</b> 만족’."},
 {"no":35,"text":"We should focus on trying to identify ▢ we are losing so many customers to other businesses.",
  "opts":["what","which","why","whose"],"ans":2,"type":"의문사·명사절","selfkey":True,
  "expl":"‘<b>왜</b> 고객을 잃는지 파악’ → why(완전한 절을 이끄는 이유의 의문사)."},
 {"no":36,"text":"This contract was an important deal ▢ us to stay on schedule and finish the first stage of product design and development.",
  "opts":["according to","so as to","would like to","in order for"],"ans":3,"type":"부정사·목적","selfkey":True,
  "expl":"의미상 주어 us가 있으므로 ‘<b>in order for</b> + 목적어 + to부정사’."},
 {"no":37,"text":"We pride ▢ on our commitment to providing for our clients in every way.",
  "opts":["us","our","we","ourselves"],"ans":3,"type":"대명사·재귀","selfkey":True,
  "expl":"‘pride <b>oneself</b> on(~을 자부하다)’ → ourselves."},
 {"no":38,"text":"Heavy lifting and other ▢ tasks may occasionally be required if you apply for a full-time janitor position.",
  "opts":["contemporary","strenuous","prolific","complimentary"],"ans":1,"type":"어휘·형용사","selfkey":True,
  "expl":"‘무거운 것 들기’와 어울리는 ‘<b>힘든(strenuous)</b> 업무’.","vocab":[("strenuous","격렬한·힘든"),("janitor","관리인")]},
 {"no":39,"text":"Her ▢ for fashion and her proficiency in sales management make her a true asset to our company.",
  "opts":["enthusiastic","enthusiastically","enthusiasm","enthusiast"],"ans":2,"type":"품사·명사","selfkey":True,
  "expl":"소유격 Her 뒤 명사 자리이며 ‘~에 대한 열정’ → <b>enthusiasm</b> for. enthusiast(애호가·사람)는 의미가 안 맞는다.","vocab":[("proficiency","능숙함"),("asset","자산")]},
 {"no":40,"text":"Visitors will have to climb the stairs if they need to visit the restrooms, as there are ▢ elevators to use.",
  "opts":["none","no","not","nothing"],"ans":1,"type":"수량형용사","selfkey":True,
  "expl":"명사 elevators 앞에서 ‘~이 없는’을 뜻하는 <b>no</b>. none은 대명사라 뒤에 명사를 못 붙인다."},
 {"no":41,"text":"The conference venue was specifically chosen due to its ▢ to the famous Edinburgh Theater in downtown.",
  "opts":["promise","proximity","duplication","recipient"],"ans":1,"type":"어휘·명사","selfkey":True,
  "expl":"‘~에 대한 <b>근접성(proximity to)</b>’ 때문에 선정.","vocab":[("proximity","근접성")]},
 {"no":42,"text":"After graduating with a degree in public relations, Ms. Channing decided she would prefer to be her ▢ boss rather than work for someone else.",
  "opts":["one","it","own","owing"],"ans":2,"type":"형용사·강조","selfkey":True,
  "expl":"‘be one’s <b>own</b> boss(자기 사업을 하다)’."},
 {"no":43,"text":"Since the company plans a ▢ of events, all employees are required to work extra hours.",
  "opts":["vary","various","variety","variable"],"ans":2,"type":"어휘·명사","selfkey":True,
  "expl":"‘a <b>variety</b> of events(다양한 행사)’ 관용 표현."},
 {"no":44,"text":"When ▢ the airport limousine service, you will be asked to indicate your flight number.",
  "opts":["attending","conforming","reserving","riding"],"ans":2,"type":"어휘·동사","selfkey":True,
  "expl":"항공편 번호를 묻는 맥락 → ‘<b>예약할(reserving)</b> 때’."},
 {"no":45,"text":"Ms. Blake is still new at Ribena, but her teammates consider her a highly ▢ employee in regard to creating original Web content.",
  "opts":["productive","productively","producing","produce"],"ans":0,"type":"품사·형용사","selfkey":True,
  "expl":"명사 employee를 수식하는 형용사 <b>productive</b>(부사 highly의 수식을 받음)."},
 {"no":46,"text":"A part-time worker has been hired at the library to help ▢ the archives on the 2nd and 3rd floors.",
  "opts":["organize","organizing","organization","organizes"],"ans":0,"type":"동사·형태","selfkey":True,
  "expl":"‘help + (to) 동사원형’ → help <b>organize</b>(정리하는 것을 돕다).","vocab":[("archives","기록보관소")]},
 {"no":47,"text":"At Eurovision Online, ▢ articles received before the submission deadline will be published on the website.",
  "opts":["every","either","neither","all"],"ans":3,"type":"수량형용사","selfkey":True,
  "expl":"복수명사 articles 앞이므로 <b>all</b>. every는 단수명사와 쓴다."},
 {"no":48,"text":"Farmers in the Saint Barthelemy region have recently begun growing a variety of organic grapes, and the responses from consumers have been ▢ favorable so far.",
  "opts":["a lot","much","very","some"],"ans":2,"type":"부사","selfkey":True,
  "expl":"형용사 favorable을 수식하는 <b>very</b>(매우). a lot/much는 비교급·동사 수식용."},
 {"no":49,"text":"All employees must ▢ with the office building’s new policy regarding recycling and hygiene.",
  "opts":["fulfill","perform","comply","observe"],"ans":2,"type":"어휘·동사","selfkey":True,
  "expl":"뒤의 전치사 with와 결합하는 ‘<b>comply</b> with(준수하다)’. observe는 with 없이 목적어를 취한다."},
 {"no":50,"text":"Employees who fail this Thursday’s computer proficiency test will be ▢ to additional training.",
  "opts":["subject","limited","accountable","preferred"],"ans":0,"type":"어휘·형용사","selfkey":True,
  "expl":"‘be <b>subject</b> to(~을 받게 되다·적용받다)’ → 추가 교육 대상."},
 {"no":51,"text":"SerenScape Spa Salon offers the most ▢ range of beauty treatments in the county.",
  "opts":["quiet","friendly","spacious","extensive"],"ans":3,"type":"어휘·형용사","selfkey":True,
  "expl":"‘가장 <b>광범위한(extensive)</b> 종류’.","vocab":[("extensive","광범위한")]},
 {"no":52,"text":"▢ a new marketing campaign before the grand opening is one of the most important steps in running this business.",
  "opts":["Create","Creating","Creative","Creation"],"ans":1,"type":"동명사·주어","selfkey":True,
  "expl":"문장의 주어이면서 목적어(a campaign)를 이끄는 <b>동명사 Creating</b>."},
 {"no":53,"text":"Delivered in ▢ boxes, BloomGlow Boutique gift items reflect the sophisticated style and environmental awareness of the company.",
  "opts":["reuse","reuses","reusing","reusable"],"ans":3,"type":"품사·형용사","selfkey":True,
  "expl":"명사 boxes를 수식하는 형용사 <b>reusable</b>(재사용 가능한).","vocab":[("sophisticated","세련된")]},
 {"no":54,"text":"At our restaurant, we consider the number of returning diners a useful ▢ of customer satisfaction.",
  "opts":["indicator","applicator","operator","provider"],"ans":0,"type":"어휘·명사","selfkey":True,
  "expl":"‘고객 만족도의 유용한 <b>지표(indicator)</b>’."},
 {"no":55,"text":"An ▢ number of advance orders indicated that the new device would be a best-selling item.",
  "opts":["understandable","unprecedented","inappropriate","inefficient"],"ans":1,"type":"어휘·형용사","selfkey":True,
  "expl":"베스트셀러를 예고하는 ‘<b>전례 없는(unprecedented)</b> 수’.","vocab":[("unprecedented","전례 없는")]},
 {"no":56,"text":"The Marketing Department at OasisVibe Beverages was surprised to see how ▢ the new fitness drink’s popularity rose after the celebrity endorsement.",
  "opts":["quickness","quicken","quickly","quickest"],"ans":2,"type":"품사·부사","selfkey":True,
  "expl":"동사 rose를 수식하는 부사 <b>quickly</b>(how quickly ~ rose).","vocab":[("endorsement","(유명인의) 홍보·보증")]},
 {"no":57,"text":"The packaging for our products should be ▢ recognizable in order to increase our revenue in this competitive market.",
  "opts":["urgently","finally","instantly","terribly"],"ans":2,"type":"어휘·부사","selfkey":True,
  "expl":"‘<b>즉시(instantly)</b> 알아볼 수 있는’."},
 {"no":58,"text":"When the transfer is ▢, please send a message confirming the receipt of payment.",
  "opts":["whole","entire","complete","total"],"ans":2,"type":"어휘·형용사","selfkey":True,
  "expl":"‘이체가 <b>완료되면(complete)</b>’ — be동사 뒤 보어. whole/entire/total은 이 뜻으로 서술적으로 못 쓴다."},
 {"no":59,"text":"Since the performance had a low turnout, guests were invited to sit in ▢ seats were still empty.",
  "opts":["whoever","whenever","whichever","wherever"],"ans":2,"type":"복합관계사","selfkey":True,
  "expl":"명사 seats를 한정하는 ‘<b>whichever</b> seats(비어 있는 어느 좌석에든)’.","vocab":[("turnout","참석자 수")]},
 {"no":60,"text":"Hotel guests can have their poolside beverages and food ▢ billed to their room.",
  "opts":["automatically","automatic","automates","automate"],"ans":0,"type":"품사·부사","selfkey":True,
  "expl":"분사 billed를 수식하는 부사 <b>automatically</b>(자동으로)."},
 {"no":61,"text":"There are various nutrition supplements that can help ▢ lose weight.",
  "opts":["you","your","yourself","yourselves"],"ans":0,"type":"대명사·목적격","selfkey":True,
  "expl":"‘help + 목적어 + 동사원형’ → help <b>you</b> lose weight."},
 {"no":62,"text":"It is ▢ that residents be reminded about the water usage restrictions that will come into effect next week.",
  "opts":["sudden","critical","specific","cautious"],"ans":1,"type":"어휘·형용사(당위)","selfkey":True,
  "expl":"당위(that + 원형 be)를 유발하는 이성적 판단 형용사 <b>critical</b>(중요한)."},
 {"no":63,"text":"Rainbow Bar & Bistro has been closed temporarily ▢ complaints about kitchen hygiene standards.",
  "opts":["although","so that","as for","due to"],"ans":3,"type":"전치사","selfkey":True,
  "expl":"뒤에 명사구가 오는 ‘~때문에’ → <b>due to</b>. although/so that는 절이 필요."},
 {"no":64,"text":"Ticket holders are encouraged to take their seats at least fifteen minutes before the concert’s ▢ start time.",
  "opts":["schedules","schedule","scheduling","scheduled"],"ans":3,"type":"품사·분사","selfkey":True,
  "expl":"명사구 start time을 수식하는 분사형용사 <b>scheduled</b>(예정된)."},
 {"no":65,"text":"Please be aware that our recorded stock levels tend to change ▢ as new orders are placed through our web store.",
  "opts":["evenly","hourly","properly","barely"],"ans":1,"type":"어휘·부사","selfkey":True,
  "expl":"주문이 들어올 때마다 자주 바뀐다는 맥락 → ‘<b>시간마다(hourly)</b>’."},
 {"no":66,"text":"Our comprehensive online FAQ page will help you overcome any obstacles you may ▢ while setting up Internet banking.",
  "opts":["transfer","consider","encounter","administer"],"ans":2,"type":"어휘·동사","selfkey":True,
  "expl":"‘마주칠 수 있는 장애물’ → obstacles you may <b>encounter</b>.","vocab":[("obstacle","장애물")]},
 {"no":67,"text":"Coffee packets ▢ with yellow stickers are included in this month’s buy-one-get-one-free offer.",
  "opts":["marked","marking","that mark","are marked"],"ans":0,"type":"품사·분사","selfkey":True,
  "expl":"본동사 are included가 이미 있으므로 명사 packets를 수식하는 과거분사 <b>marked</b>(스티커가 붙은)."},
 {"no":68,"text":"The first workday of every year is ▢ the president of Kario Enterprises circulates a company-wide memo.",
  "opts":["what","for","when","how"],"ans":2,"type":"관계부사·보어","selfkey":True,
  "expl":"‘~하는 <b>때</b>이다’ → is when(시간을 보충하는 관계부사)."},
 {"no":69,"text":"Technical issues that require ▢ attention should be addressed before any relatively minor problems.",
  "opts":["near","fluent","absent","urgent"],"ans":3,"type":"어휘·형용사","selfkey":True,
  "expl":"사소한 문제보다 먼저 처리 → ‘<b>긴급한(urgent)</b> 주의’."},
 {"no":70,"text":"Mr. Palance has requested to see the maintenance report for the photocopier that ▢.",
  "opts":["repairs","repairing","repaired","was repaired"],"ans":3,"type":"동사·태","selfkey":True,
  "expl":"관계절의 동사 자리이며 복사기는 수리‘되는’ 대상이므로 수동 <b>was repaired</b>."},
 {"no":71,"text":"To ensure the accuracy of our findings, the survey questions should remain ▢ the same during the course of the month-long study.",
  "opts":["exacted","exactness","exact","exactly"],"ans":3,"type":"품사·부사","selfkey":True,
  "expl":"‘the same’을 강조하는 부사 <b>exactly</b>(정확히 똑같이 유지)."},
 {"no":72,"text":"According to a government report, the demand for oil is ▢ despite the recent global economic downturn.",
  "opts":["expand","expands","be expanded","expanding"],"ans":3,"type":"동사·형태","selfkey":True,
  "expl":"‘is + -ing(현재진행)’ → 수요가 <b>증가하고 있다(expanding)</b>.","vocab":[("downturn","침체")]},
 {"no":73,"text":"At Kovacs Chemical Inc., you may request to join the health and safety committee if you have ▢ five classes of first aid training.",
  "opts":["applied","completed","projected","extended"],"ans":1,"type":"어휘·동사","selfkey":True,
  "expl":"‘응급처치 교육 5개를 <b>이수했다면(completed)</b>’."},
 {"no":74,"text":"The new headphones released by Volter Electronics eliminate all external sound, even ▢ the loudest sources of noise.",
  "opts":["up","from","upon","between"],"ans":1,"type":"전치사","selfkey":True,
  "expl":"‘~로부터 소음을 제거’ → eliminate sound <b>from</b> the sources."},
 {"no":75,"text":"Tim Finnegan received an award in ▢ of his marked improvement in terms of sales figures and work ethic.",
  "opts":["recognition","comprehension","identification","significance"],"ans":0,"type":"어휘·명사(관용)","selfkey":True,
  "expl":"‘in <b>recognition</b> of(~을 인정하여)’ 관용 표현.","vocab":[("work ethic","직업 윤리")]},
 {"no":76,"text":"In accordance with the ▢ of this agreement, you are required to submit your freelance work assignments no later than 5 p.m. each day.",
  "opts":["opinions","terms","designs","applications"],"ans":1,"type":"어휘·명사","selfkey":True,
  "expl":"‘계약의 <b>조건(terms)</b>에 따라’.","vocab":[("in accordance with","~에 따라")]},
 {"no":77,"text":"The report based on the recently compiled market research findings only includes details that are ▢ to our current projects.",
  "opts":["acceptable","completed","relevant","certain"],"ans":2,"type":"어휘·형용사","selfkey":True,
  "expl":"전치사 to와 결합하여 ‘~와 <b>관련 있는(relevant to)</b>’."},
 {"no":78,"text":"Please upload your résumé to our recruitment web site ▢ employers can contact you regarding future vacancies.",
  "opts":["so that","in order to","because of","as well as"],"ans":0,"type":"접속사·목적","selfkey":True,
  "expl":"뒤에 절(employers can ~)이 오므로 ‘~하도록’의 <b>so that</b>. in order to는 뒤에 동사원형이 온다.","vocab":[("vacancy","공석")]},
 {"no":79,"text":"Grundy’s Seafood has relocated to Helmet Island, just ▢ the Memorial Bridge.",
  "opts":["across","about","outside","between"],"ans":0,"type":"전치사","selfkey":True,
  "expl":"‘다리 바로 <b>건너편에</b>’ → just across."},
 {"no":80,"text":"Since the new marketing strategy was well researched and effectively implemented, customers are expected to react ▢ to the newly launched sports drink.",
  "opts":["internationally","favorably","willingly","completely"],"ans":1,"type":"어휘·부사","selfkey":True,
  "expl":"좋은 전략의 결과 → ‘<b>호의적으로(favorably)</b> 반응’."},
 {"no":81,"text":"Ms. Simpson has given ▢ an extended deadline for completing the market research survey.",
  "opts":["we","us","our","ourselves"],"ans":1,"type":"대명사·목적격","selfkey":True,
  "expl":"‘give + 간접목적어’ → has given <b>us</b>(우리에게)."},
 {"no":82,"text":"Mr. Singh said that to meet the high demand of the tax season, ▢ must work on Saturdays throughout March and April.",
  "opts":["no","something","one another","everyone"],"ans":3,"type":"대명사·주어","selfkey":True,
  "expl":"절의 주어로 ‘<b>모두(everyone)</b>가 일해야 한다’."},
 {"no":83,"text":"▢ route the delivery trucks take, shipment will take longer than expected due to the peak holiday season.",
  "opts":["When","While","Whether","Whichever"],"ans":3,"type":"복합관계사","selfkey":True,
  "expl":"명사 route를 한정하며 ‘어떤 경로를 택하든’ → <b>Whichever</b> route."},
 {"no":84,"text":"▢ who wishes to take part in the computer skills workshop on August 2 should contact Ms. Gilchrist by the end of next week.",
  "opts":["Others","They","Herself","Anyone"],"ans":3,"type":"대명사·주어","selfkey":True,
  "expl":"‘~하고자 하는 <b>누구든(Anyone)</b>’ — 단수 취급하여 뒤의 wishes와 호응."},
 {"no":85,"text":"The fee you paid ▢ both your hotel accommodations and registration for this conference.",
  "opts":["wraps","covers","guards","spreads"],"ans":1,"type":"어휘·동사","selfkey":True,
  "expl":"‘요금이 ~을 <b>포함한다(covers)</b>’."},
 {"no":86,"text":"According to the instructions concerning lectures at the genetics conference, 40 minutes is the maximum ▢ of a presentation.",
  "opts":["length","instant","attention","significance"],"ans":0,"type":"어휘·명사","selfkey":True,
  "expl":"‘발표의 최대 <b>길이(length)</b>는 40분’."},
 {"no":87,"text":"We are looking for an experienced architect ▢ in sustainable design to help our expanding business in urban development.",
  "opts":["promoting","implementing","specializing","engaging"],"ans":2,"type":"어휘·동사","selfkey":True,
  "expl":"‘~을 <b>전문으로 하는(specializing in)</b>’ 건축가."},
 {"no":88,"text":"Every year, Laporte University hosts a ▢ of seminars led by experts in medical research.",
  "opts":["present","scheme","series","progression"],"ans":2,"type":"어휘·명사","selfkey":True,
  "expl":"‘a <b>series</b> of seminars(일련의 세미나)’."},
 {"no":89,"text":"Over the past year, professional basketball player Dwayne Hounsou has earned around $40 million in salary and ▢ more from endorsements.",
  "opts":["all","very","any","even"],"ans":3,"type":"부사·비교강조","selfkey":True,
  "expl":"비교급 more를 강조하는 <b>even</b>(‘게다가 더’)."},
 {"no":90,"text":"Government officials agreed to take a stronger ▢ on piracy and start taking measures to ensure that state-owned organizations are only using legal software.",
  "opts":["stance","circumstance","composition","circuit"],"ans":0,"type":"어휘·명사","selfkey":True,
  "expl":"‘~에 대해 더 강경한 <b>입장(stance)</b>을 취하다’.","vocab":[("piracy","불법 복제")]},
 {"no":91,"text":"Watson Consulting is collecting information from a wide range of sources to create a ▢ directory of businesses in this area.",
  "opts":["variable","incidental","redundant","comprehensive"],"ans":3,"type":"어휘·형용사","selfkey":True,
  "expl":"다양한 출처를 모아 만드는 ‘<b>포괄적인(comprehensive)</b> 명부’.","vocab":[("comprehensive","포괄적인")]},
 {"no":92,"text":"Please make a poster promoting all of the musicians who will be performing at the Rashford Theater ▢.",
  "opts":["yet","soon","lately","previously"],"ans":1,"type":"어휘·부사","selfkey":True,
  "expl":"미래(will be performing)와 어울리는 ‘<b>곧(soon)</b>’. lately/previously는 과거."},
 {"no":93,"text":"▢ team can request a project extension by submitting a written proposal to the board by tomorrow afternoon.",
  "opts":["In spite of","Until","Either","Both"],"ans":2,"type":"수량형용사","selfkey":True,
  "expl":"단수명사 team 앞에서 ‘어느 팀이든’ → <b>Either</b>. Both는 복수명사와 쓴다."},
 {"no":94,"text":"Mr. Sanderson cleaned most of the factory machines while he ▢ for the safety inspection.",
  "opts":["preparing","will prepare","was preparing","had prepared"],"ans":2,"type":"동사·시제","selfkey":True,
  "expl":"과거의 동시 진행 → ‘while he <b>was preparing</b>(준비하는 동안)’."},
 {"no":95,"text":"Mr. Royle will present his research findings to the board members ▢ the monthly meeting is held.",
  "opts":["so","when","because","although"],"ans":1,"type":"접속사","selfkey":True,
  "expl":"‘월례 회의가 열릴 <b>때(when)</b>’."},
 {"no":96,"text":"The problem that needs ▢ immediately is not just about the budget but about the approval for the construction.",
  "opts":["address","addressing","to be addressed","being addressed"],"ans":2,"type":"동사·태","selfkey":True,
  "expl":"‘need + to be p.p.(수동)’ → needs <b>to be addressed</b>(해결되어야 한다).",
  "warn":"엄밀히는 (B) addressing도 ‘need + 동명사 = 수동’ 용법으로 문법상 성립합니다. 원본에 정답이 없어, 더 표준적인 (C) to be addressed를 정답으로 제시했습니다."},
 {"no":97,"text":"The restaurant manager does not mind ▢ customers in the dining area during particularly busy periods.",
  "opts":["serve","serving","to serve","to be served"],"ans":1,"type":"동명사","selfkey":True,
  "expl":"‘mind + 동명사’ → does not mind <b>serving</b>(응대하는 것을 꺼리지 않다)."},
 {"no":98,"text":"▢ four weeks, Smartsave Foods Inc. publishes a company newsletter that is distributed to all employees.",
  "opts":["During","Every","About","Only"],"ans":1,"type":"수량형용사","selfkey":True,
  "expl":"‘<b>Every</b> four weeks(4주마다)’ — 주기를 나타낸다."},
 {"no":99,"text":"Brightline Construction intends to close down ▢ the next few days due to financial difficulties.",
  "opts":["nearly","within","at","pertaining to"],"ans":1,"type":"전치사","selfkey":True,
  "expl":"‘며칠 <b>이내에(within)</b>’ 폐업."},
 {"no":100,"text":"Maintenance personnel at Blue Horizon Hotel are asked to address the problems that are ▢ in the inspection reports.",
  "opts":["identified","to identify","identification","identifying"],"ans":0,"type":"동사·태","selfkey":True,
  "expl":"관계절 ‘that are ___’에서 문제(problems)는 확인‘되는’ 대상이므로 과거분사 <b>identified</b>."},
]
