# -*- coding: utf-8 -*-
"""
토익응급실 최신 Part 5 변형 3세트 (260228 / 260329 / 260426), 각 30문항.
- text의 '▢' 가 빈칸 위치.
- 각 문항의 ans(정답 인덱스)는 원본 제공 정답과 대조·검산 완료(verified=True).
- provided_key_* : 원본 하단 제공 정답. verify.py 가 ans와 자동 대조.
"""

# 원본 제공 정답 (하단 [정답])
provided_key_228 = "A B C D C A B D A A B A C D A D B D D C B B A D D D C B C A"
provided_key_329 = "B A C B B D B B B A C A B D B A C C A D A C D A C B A C C A"
provided_key_426 = "B A C B A B C D C A D D C D D D B C A B D A D C A B D D C B"

set228 = [
 {"no":101,"text":"EvaSphere Retail plans to open flagship stores in major cities ▢ the globe.",
  "opts":["across","between","outside","toward"],"ans":0,"type":"전치사","verified":True,
  "expl":"‘전 세계에 걸쳐’를 뜻하는 <b>across the globe</b>가 정답. between(둘 사이)·outside·toward는 문맥에 안 맞는다.",
  "vocab":[("flagship store","대표 매장")]},
 {"no":102,"text":"We provides full refunds to customers who are not completely ▢ with their purchases.",
  "opts":["satisfaction","satisfied","satisfactory","satisfies"],"ans":1,"type":"분사형용사","verified":True,
  "expl":"‘be <b>satisfied</b> with(~에 만족하다)’. 사람(customers)이 만족을 느끼는 대상이므로 과거분사 satisfied.",
  "warn":"원본 오타: ‘We <u>provides</u>’ → 주어-동사 불일치(‘We provide’ 또는 ‘It provides’가 맞음). 정답과는 무관."},
 {"no":103,"text":"Beginning March 1, Ms. Garcia will serve as the operations manager at the production ▢.",
  "opts":["residence","routine","facility","career"],"ans":2,"type":"어휘·명사","verified":True,
  "expl":"‘생산 시설’을 뜻하는 <b>production facility</b>가 정답. 근무 ‘장소’를 나타낸다.",
  "vocab":[("facility","시설")]},
 {"no":104,"text":"The cleaning equipment was ▢ damaged in transit, so it needs only minor repairs.",
  "opts":["nearly","solidly","slowly","partially"],"ans":3,"type":"어휘·부사","verified":True,
  "expl":"‘경미한 수리만 필요’와 이어지려면 ‘부분적으로 손상’이어야 하므로 <b>partially</b>가 정답.",
  "vocab":[("in transit","운송 중"),("partially","부분적으로")]},
 {"no":105,"text":"▢ for how to submit reimbursement claims can be found on the company’s internal website.",
  "opts":["Instructive","Instructed","Instructions","Instructs"],"ans":2,"type":"품사·명사(주어)","verified":True,
  "expl":"문장의 <b>주어</b> 자리 명사. 복수 주어로 ‘Instructions ... can be found’가 자연스럽다.",
  "vocab":[("reimbursement","환급")]},
 {"no":106,"text":"The most ▢ result of the budget reduction will be fewer training opportunities for new employees.",
  "opts":["likely","unavailable","interested","external"],"ans":0,"type":"어휘·형용사","verified":True,
  "expl":"‘가장 가능성 높은 결과’를 뜻하는 <b>the most likely result</b>가 정답."},
 {"no":107,"text":"Harbor Street Books will order special titles for customers ▢ they cannot find them in the store.",
  "opts":["although","if","thus","unless"],"ans":1,"type":"접속사","verified":True,
  "expl":"‘매장에서 못 찾으면 주문해 준다’는 조건이므로 <b>if</b>가 정답. unless(~하지 않는 한)는 논리가 반대."},
 {"no":108,"text":"According to recent survey results, young professionals are ▢ interested in flexible working hours.",
  "opts":["intensity","intense","intensify","intensely"],"ans":3,"type":"품사·부사","verified":True,
  "expl":"형용사 interested를 수식하는 <b>부사</b> 자리 → intensely(대단히)."},
 {"no":109,"text":"Dr. Fletcher recently gave a talk on renewable energy ▢ the international sustainability conference.",
  "opts":["during","under","inside","beside"],"ans":0,"type":"전치사","verified":True,
  "expl":"‘학회 <b>동안/에서</b>’를 뜻하는 during이 정답.",
  "vocab":[("renewable energy","재생 에너지")]},
 {"no":110,"text":"Since organic food is a growing trend, ▢ of GreenLeaf’s fruits are grown without chemical fertilizers.",
  "opts":["many","whose","them","much"],"ans":0,"type":"수량형용사","verified":True,
  "expl":"가산 복수(fruits)이고 동사가 are이므로 <b>many</b>. much는 불가산 명사에 쓴다.",
  "vocab":[("fertilizer","비료")]},
 {"no":111,"text":"Because of safety concerns, Gymlego Sports has delayed the planned ▢ of its distribution center.",
  "opts":["safety","expansion","confinement","status"],"ans":1,"type":"어휘·명사","verified":True,
  "expl":"‘계획된 <b>확장</b>을 연기했다’가 자연스럽다 → expansion.",
  "vocab":[("distribution center","물류 센터")]},
 {"no":112,"text":"To reach our customer service team ▢, please dial the extension listed on the contact page.",
  "opts":["directly","directing","directional","directed"],"ans":0,"type":"품사·부사","verified":True,
  "expl":"동사 reach를 수식하는 부사 <b>directly</b>(직접)."},
 {"no":113,"text":"Ms. Ramirez expects the maintenance work on the third floor to be finished ▢ the end of the day.",
  "opts":["behind","among","by","along"],"ans":2,"type":"전치사·시간","verified":True,
  "expl":"‘하루가 끝날 때까지 완료(완료 시점)’이므로 <b>by</b>."},
 {"no":114,"text":"Employees may use the newly renovated cafeteria ▢ the paint on the wall has completely dried.",
  "opts":["while","ever","later than","as soon as"],"ans":3,"type":"접속사","verified":True,
  "expl":"‘페인트가 다 마르는 <b>즉시</b> 사용 가능’ → as soon as. while(~하는 동안)은 논리에 안 맞는다."},
 {"no":115,"text":"Silverside Medical Center provides online reminders for patients ▢ they book through the Web site.",
  "opts":["when","because","that","so"],"ans":0,"type":"접속사","verified":True,
  "expl":"‘예약할 <b>때</b> 알림을 제공’ → when."},
 {"no":116,"text":"The famous restaurant’s sudden ▢ shocked many loyal customers in the neighborhood.",
  "opts":["closes","closer","closed","closing"],"ans":3,"type":"품사·명사","verified":True,
  "expl":"형용사 sudden 뒤 <b>명사(동명사) 자리</b> → closing(폐업)."},
 {"no":117,"text":"One of the proposals ▢ by the committee has been approved with unanimous consent for immediate implementation.",
  "opts":["initiating","initiated","initiator","initiation"],"ans":1,"type":"품사·분사","verified":True,
  "expl":"‘위원회에 의해 발의된’ 수동 의미 → 과거분사 <b>initiated</b>(proposals 수식).",
  "vocab":[("unanimous","만장일치의")]},
 {"no":118,"text":"Staff members should be ▢ with their schedules during the peak holiday season.",
  "opts":["possible","significant","personal","flexible"],"ans":3,"type":"어휘·형용사","verified":True,
  "expl":"‘일정에 <b>융통성 있게</b>’ → be flexible with."},
 {"no":119,"text":"Dr. Hernandez has ▢ herself to treating infectious diseases for many years at St. Andrew Medical Center.",
  "opts":["studied","removed","informed","dedicated"],"ans":3,"type":"어휘·동사","verified":True,
  "expl":"‘dedicate oneself to ~ing(~에 헌신하다)’ → dedicated.",
  "vocab":[("infectious disease","전염병")]},
 {"no":120,"text":"The recent campaign was a ▢ effort to increase awareness of the company’s new services.",
  "opts":["successfully","success","successful","succeed"],"ans":2,"type":"품사·형용사","verified":True,
  "expl":"명사 effort를 수식하는 형용사 <b>successful</b>."},
 {"no":121,"text":"The results of the neighborhood survey confirmed that emergency services in the area are ▢ accessible.",
  "opts":["reading","readily","ready","readied"],"ans":1,"type":"품사·부사","verified":True,
  "expl":"형용사 accessible을 수식하는 부사 <b>readily</b>(쉽게)."},
 {"no":122,"text":"Mr. Harris encourages interns to collaborate with senior editors to build résumés that ▢ their expertise.",
  "opts":["perceive","showcase","compose","receive"],"ans":1,"type":"어휘·동사","verified":True,
  "expl":"‘전문성을 <b>보여주는</b> 이력서’ → showcase.",
  "vocab":[("expertise","전문성")]},
 {"no":123,"text":"Some high-performing temporary employees will be considered for full-time positions, but ▢ will not.",
  "opts":["most","each","they","none"],"ans":0,"type":"대명사·수량","verified":True,
  "expl":"‘일부는 고려되지만 <b>대부분(most)</b>은 아니다’의 대조. none은 이중부정이 되어 부적절."},
 {"no":124,"text":"Harbor Table Bistro asks diners to provide feedback ▢ any issues they encounter during their visit.",
  "opts":["from","perhaps","which","regarding"],"ans":3,"type":"전치사","verified":True,
  "expl":"‘~에 관한 피드백’ → feedback <b>regarding</b> any issues."},
 {"no":125,"text":"Government funding was allocated ▢ to ensure fair support for all participating departments.",
  "opts":["potentially","aggressively","energetically","equitably"],"ans":3,"type":"어휘·부사","verified":True,
  "expl":"‘공정한 지원(fair support)’ 단서 → ‘공평하게’ <b>equitably</b>.",
  "vocab":[("allocate","배분하다"),("equitably","공평하게")]},
 {"no":126,"text":"Nordell office chairs are ▢ and can be purchased at a competitive price.",
  "opts":["consumable","forceful","arguable","sturdy"],"ans":3,"type":"어휘·형용사","verified":True,
  "expl":"의자의 속성으로 ‘튼튼한’ <b>sturdy</b>가 자연스럽다.",
  "vocab":[("sturdy","튼튼한")]},
 {"no":127,"text":"The company’s long-term strategy is ▢ based on customer feedback from regional markets.",
  "opts":["larger","largest","largely","large"],"ans":2,"type":"품사·부사","verified":True,
  "expl":"분사 based를 수식하는 부사 <b>largely</b>(대체로). ‘is largely based on’."},
 {"no":128,"text":"Dr. Molina’s research supports the idea that highly ▢ individuals solve complex problems in unconventional ways.",
  "opts":["creatively","creative","create","created"],"ans":1,"type":"품사·형용사","verified":True,
  "expl":"명사 individuals를 수식하는 형용사 <b>creative</b>(부사 highly의 수식을 받음)."},
 {"no":129,"text":"The robust design of outdoor storage containers guarantees their ▢ even under harsh conditions.",
  "opts":["responsibility","sensibility","durability","eventuality"],"ans":2,"type":"어휘·명사","verified":True,
  "expl":"‘견고한 설계 → <b>내구성</b> 보장’ → durability.",
  "vocab":[("robust","견고한"),("durability","내구성")]},
 {"no":130,"text":"To ensure it ▢ sufficient inventory, Harbor Lane Market reviews its stock levels every morning.",
  "opts":["maintains","maintenance","maintaining","was maintained"],"ans":0,"type":"동사·형태","verified":True,
  "expl":"주어 it(=Market)의 현재시제 능동 동사 <b>maintains</b>(충분한 재고를 유지)."},
]

set329 = [
 {"no":101,"text":"Brightline Hotel is having its old conference room ▢ to accommodate larger corporate events.",
  "opts":["remodeling","remodeled","to remodel","remodels"],"ans":1,"type":"분사·사역","verified":True,
  "expl":"‘have + 목적어 + 과거분사(수동)’: 방이 ‘리모델링되게 하다’ → <b>remodeled</b>."},
 {"no":102,"text":"The repair work on the main office building is expected to be completed ▢ three weeks.",
  "opts":["within","against","beneath","along"],"ans":0,"type":"전치사","verified":True,
  "expl":"‘3주 <b>이내에</b> 완료’ → within."},
 {"no":103,"text":"WillMart makes every effort to ensure a pleasant shopping ▢ for all customers.",
  "opts":["training","amusement","experience","intelligence"],"ans":2,"type":"어휘·명사","verified":True,
  "expl":"‘쾌적한 쇼핑 <b>경험</b>’ → shopping experience."},
 {"no":104,"text":"At the ▢ staff meeting, Ms. Garcia will introduce the new team members and their responsibilities.",
  "opts":["ordinary","initial","attentive","invited"],"ans":1,"type":"어휘·형용사","verified":True,
  "expl":"신입을 소개하는 ‘<b>첫(initial)</b> 회의’가 문맥에 맞는다."},
 {"no":105,"text":"Horizon Securities provides its clients ▢ investment options which can be tailored to their financial goals.",
  "opts":["flexibility","flexible","flexibly","flexed"],"ans":1,"type":"품사·형용사","verified":True,
  "expl":"명사 options를 수식하는 형용사 <b>flexible</b>(유연한)."},
 {"no":106,"text":"The new mobile application is ▢ designed to improve user engagement across platforms.",
  "opts":["imagination","imaginative","imaginary","imaginatively"],"ans":3,"type":"품사·부사","verified":True,
  "expl":"분사 designed를 수식하는 부사 <b>imaginatively</b>(창의적으로)."},
 {"no":107,"text":"The executive committee will meet ▢ deciding on the final budget proposal for next quarter.",
  "opts":["except","before","through","to"],"ans":1,"type":"전치사·시간","verified":True,
  "expl":"‘결정하기 <b>전에</b> 만난다’ → before + 동명사(deciding)."},
 {"no":108,"text":"The annual company workshop for new employees will take place ▢ this month.",
  "opts":["last","later","behind","finish"],"ans":1,"type":"어휘·부사","verified":True,
  "expl":"‘이달 <b>말경(later this month)</b>에 열린다’ → later."},
 {"no":109,"text":"The Redwood National Park website provides a ▢ of each hiking trail along with maps.",
  "opts":["solution","description","length","possibility"],"ans":1,"type":"어휘·명사","verified":True,
  "expl":"‘각 등산로에 대한 <b>설명</b>’ → description."},
 {"no":110,"text":"At Maple Grove Bistro, ▢ customers’ satisfaction is the top priority.",
  "opts":["our","ourselves","ours","us"],"ans":0,"type":"대명사·소유격","verified":True,
  "expl":"명사(customers’) 앞 소유격 <b>our</b>."},
 {"no":111,"text":"AeroLynx Airlines continues to surpass its competitors ▢ strong competition in the aviation industry.",
  "opts":["although","instead of","despite","contrary to"],"ans":2,"type":"전치사","verified":True,
  "expl":"뒤에 명사구가 오는 ‘~에도 불구하고’ → <b>despite</b>. although는 절이 필요.",
  "vocab":[("surpass","능가하다")]},
 {"no":112,"text":"Nexora Solutions strives to keep costs low, as ▢ is critical for maintaining long-term profitability.",
  "opts":["that","what","such","each"],"ans":0,"type":"대명사","verified":True,
  "expl":"앞의 ‘비용을 낮게 유지하는 것’을 가리키는 지시대명사 <b>that</b>이 주어. ‘as that is critical’."},
 {"no":113,"text":"Ms. Harper cannot attend the staff meeting ▢ she has a mandatory training session scheduled at the same time.",
  "opts":["otherwise","because","unless","yet"],"ans":1,"type":"접속사","verified":True,
  "expl":"‘필수 교육이 있어서(이유)’ → because."},
 {"no":114,"text":"▢ our Web site to learn more about our latest services and upcoming events.",
  "opts":["To visit","Visiting","Visits","Visit"],"ans":3,"type":"명령문","verified":True,
  "expl":"주어 없이 동사원형으로 시작하는 <b>명령문</b> → Visit."},
 {"no":115,"text":"Mr. Bennett ▢ planned to join the retirement party, but a number of tasks prevented him from attending.",
  "opts":["early","originally","especially","regularly"],"ans":1,"type":"어휘·부사","verified":True,
  "expl":"‘<b>원래</b> 참석하려 했으나 ~’의 대조 흐름 → originally."},
 {"no":116,"text":"The new marketing director has experience in ▢ with the public, making well suited for the role.",
  "opts":["working","arriving","observing","handling"],"ans":0,"type":"어휘·동명사","verified":True,
  "expl":"‘대중과 <b>함께 일한(working with)</b> 경험’ → working. handle은 with 없이 목적어를 취한다.",
  "warn":"원본 오타: ‘making <u>well</u> suited’ → 목적어 누락(‘making <u>her/him</u> well suited’). 정답과는 무관."},
 {"no":117,"text":"The annual strategy meeting will be held ▢ the executive board gathers next Monday.",
  "opts":["they","at","when","now"],"ans":2,"type":"접속사","verified":True,
  "expl":"‘이사회가 모일 <b>때</b> 열린다’ → when(시간 접속사)."},
 {"no":118,"text":"The workshop starts next Monday, ▢ which participants will engage in hands-on training sessions.",
  "opts":["around","since","during","into"],"ans":2,"type":"전치사+관계사","verified":True,
  "expl":"‘그 기간(월요일) <b>동안</b>’을 뜻하는 ‘during which’.",
  "vocab":[("hands-on","실습의")]},
 {"no":119,"text":"After implementing the new system, the workers were ▢ in completing their assigned tasks efficiently.",
  "opts":["successful","success","successfully","succeeded"],"ans":0,"type":"품사·형용사","verified":True,
  "expl":"be동사 뒤 보어 형용사 ‘be <b>successful</b> in ~ing(~에 성공적이다)’."},
 {"no":120,"text":"Registered users will be notified when the ▢ safety information for our newest refrigerator is released.",
  "opts":["dietary","motorized","difficult","updated"],"ans":3,"type":"어휘·형용사","verified":True,
  "expl":"‘<b>업데이트된</b> 안전 정보가 공개될 때’ → updated."},
 {"no":121,"text":"The operations manager ▢ to hold monthly team meetings to share important updates across departments.",
  "opts":["prefers","collaborates","cancels","negotiates"],"ans":0,"type":"어휘·동사","verified":True,
  "expl":"‘prefer to + 동사원형(~하기를 선호)’ 구조에 맞는 <b>prefers</b>."},
 {"no":122,"text":"During the briefing session, Ms. Carter will present ▢ for improving customer satisfaction.",
  "opts":["optional","to opt","options","opting"],"ans":2,"type":"품사·명사","verified":True,
  "expl":"타동사 present의 목적어 명사 <b>options</b>(선택안)."},
 {"no":123,"text":"Despite the lengthy discussion, the board members were ▢ divided on how to prioritize the budget allocations.",
  "opts":["wisely","safely","nicely","sharply"],"ans":3,"type":"어휘·부사","verified":True,
  "expl":"‘의견이 <b>첨예하게(sharply)</b> 갈렸다’가 자연스럽다.",
  "vocab":[("be divided on","~에 대해 의견이 갈리다")]},
 {"no":124,"text":"The receptionists at Grand Horizon Hotels are always ▢ and friendly when assisting their guests.",
  "opts":["courteous","sufficient","unique","essential"],"ans":0,"type":"어휘·형용사","verified":True,
  "expl":"friendly와 병렬되는 ‘<b>정중한(courteous)</b>’.",
  "vocab":[("courteous","정중한")]},
 {"no":125,"text":"The museum staff had to move rare artifacts into ▢ to protect them from potential damage during the renovation.",
  "opts":["storable","storing","storage","store"],"ans":2,"type":"품사·명사","verified":True,
  "expl":"전치사 into의 목적어 명사 ‘<b>보관(storage)</b>’. store(상점)는 의미가 안 맞는다.",
  "vocab":[("artifact","유물")]},
 {"no":126,"text":"Mr. Carter will be ▢ Green Globe Solutions at the World Innovation Forum in London.",
  "opts":["representative","representing","representation","representer"],"ans":1,"type":"동사·형태","verified":True,
  "expl":"‘will be + -ing(미래진행)’ → <b>representing</b>(대표할 것이다)."},
 {"no":127,"text":"Hugonix Systems has been ▢ the Best Technology Provider title by the Global Tech Council.",
  "opts":["awarded","promoted","controlled","shown"],"ans":0,"type":"어휘·동사","verified":True,
  "expl":"‘award A B(A에게 B를 수여)’의 수동 ‘be <b>awarded</b> the title’."},
 {"no":128,"text":"Customer service agents are responsible for handling client inquiries ▢ and providing timely solutions.",
  "opts":["professionalism","profession","professionally","professional"],"ans":2,"type":"품사·부사","verified":True,
  "expl":"동명사 handling을 수식하는 부사 <b>professionally</b>(전문적으로)."},
 {"no":129,"text":"The development team has been given ▢ to implement the new security protocol across all systems.",
  "opts":["permissively","permissiveness","permission","permissive"],"ans":2,"type":"품사·명사","verified":True,
  "expl":"‘be given <b>permission</b> to ~(허가를 받다)’의 목적어 명사."},
 {"no":130,"text":"Mr. Lawson ▢ all team members to submit their quarterly reports before the busiest season begins.",
  "opts":["expects","expectations","expecting","expectedly"],"ans":0,"type":"동사·형태","verified":True,
  "expl":"문장의 본동사 자리. ‘expect + 목적어 + to부정사’ → <b>expects</b>."},
]

set426 = [
 {"no":101,"text":"After years of testing, Orion Electronics ▢ perfected the design of its new waterproof smartphone.",
  "opts":["final","finally","finalizing","finalized"],"ans":1,"type":"품사·부사","verified":True,
  "expl":"동사 perfected를 수식하는 부사 <b>finally</b>(마침내)."},
 {"no":102,"text":"It is time to book an ▢ for your dental checkup before the busy holiday season begins.",
  "opts":["appointment","opinion","element","accommodation"],"ans":0,"type":"어휘·명사","verified":True,
  "expl":"‘진료 <b>예약</b>을 잡다’ → book an appointment."},
 {"no":103,"text":"Ms. Lopez is ▢ to represent our legal firm at the upcoming international conference.",
  "opts":["qualification","qualifies","qualified","qualifier"],"ans":2,"type":"품사·형용사","verified":True,
  "expl":"‘be <b>qualified</b> to ~(~할 자격이 있다)’ 구조."},
 {"no":104,"text":"The marketing team decided to spend more of the budget, focusing ▢ social media advertisements.",
  "opts":["over","on","in","to"],"ans":1,"type":"전치사","verified":True,
  "expl":"‘focus <b>on</b> ~(~에 집중하다)’."},
 {"no":105,"text":"Because the current rent became more expensive, the company moved to ▢ that is more affordable.",
  "opts":["another","other","it","few"],"ans":0,"type":"대명사","verified":True,
  "expl":"‘더 저렴한 <b>다른 곳(another)</b>으로 이전’. other는 명사/others 형태가 필요."},
 {"no":106,"text":"Ms. Sanders was not sure ▢ the shipment would arrive before the grand opening of the new boutique.",
  "opts":["in contrast","whether","either","as far as"],"ans":1,"type":"접속사","verified":True,
  "expl":"‘~인지 아닌지 확신 못 함’ → be not sure <b>whether</b>."},
 {"no":107,"text":"A recent survey indicated that customers would like to see ▢ variety in the organic produce section.",
  "opts":["first","during","greater","very"],"ans":2,"type":"비교·형용사","verified":True,
  "expl":"명사 variety를 수식하는 비교급 형용사 <b>greater</b>(더 다양함). very는 명사를 수식하지 못한다."},
 {"no":108,"text":"The software developers noticed that users are increasingly using the application beyond its defined ▢.",
  "opts":["balance","success","meaning","purpose"],"ans":3,"type":"어휘·명사","verified":True,
  "expl":"‘정해진 <b>용도(purpose)</b>를 넘어서’ 사용."},
 {"no":109,"text":"Mr. Lee had ▢ boarded the plane when the pilot announced a brief delay due to technical issues.",
  "opts":["once","soon","already","altogether"],"ans":2,"type":"부사","verified":True,
  "expl":"과거완료(had + p.p.)와 함께 ‘이미’를 뜻하는 <b>already</b>."},
 {"no":110,"text":"Due to severe weather conditions, RT Express is unable ▢ packages to some mountainous regions today.",
  "opts":["to deliver","delivering","delivery","deliveries"],"ans":0,"type":"부정사","verified":True,
  "expl":"‘be unable <b>to deliver</b>(~할 수 없다)’ → to부정사."},
 {"no":111,"text":"The main production line will remain inactive ▢ the conveyor belt is being inspected.",
  "opts":["because of","or","as if","while"],"ans":3,"type":"접속사","verified":True,
  "expl":"뒤에 절이 오는 ‘~하는 동안’ → <b>while</b>. because of는 명사구를 취한다."},
 {"no":112,"text":"Complete ▢ of the clinical trial will be published in the medical journal once the final review is finished.",
  "opts":["resulting","resulted","result","results"],"ans":3,"type":"품사·명사(수)","verified":True,
  "expl":"주어 자리 명사이며 ‘임상시험 결과’는 보통 복수 <b>results</b>로 쓴다.",
  "vocab":[("clinical trial","임상시험")]},
 {"no":113,"text":"The city council decided not to rebuild the city hall ▢ discovering that the historic architecture is part of its identity.",
  "opts":["under","without","after","against"],"ans":2,"type":"전치사","verified":True,
  "expl":"‘~을 알게 된 <b>후에</b>’ → after + 동명사(discovering)."},
 {"no":114,"text":"The final candidate will be selected ▢ all the background checks have been completed.",
  "opts":["that","nearly","close to","as soon as"],"ans":3,"type":"접속사","verified":True,
  "expl":"‘모든 신원조회가 완료되는 <b>즉시</b>’ → as soon as(+절)."},
 {"no":115,"text":"Some professors have decided to update their curriculum, ▢ the rapid changes in their related field.",
  "opts":["nevertheless","instead","plus","given"],"ans":3,"type":"전치사","verified":True,
  "expl":"‘~을 고려하면’을 뜻하는 전치사 <b>given</b>(+명사구)."},
 {"no":116,"text":"The two tech firms could not reach an agreement about the terms of the ▢.",
  "opts":["collaborates","collaborate","collaborative","collaboration"],"ans":3,"type":"품사·명사","verified":True,
  "expl":"‘the terms of the <b>collaboration</b>(협업의 조건)’ — 관사 the 뒤 명사."},
 {"no":117,"text":"The CEO spoke ▢ about the company’s long-term vision for sustainable energy.",
  "opts":["utterly","convincingly","famously","upwardly"],"ans":1,"type":"어휘·부사","verified":True,
  "expl":"‘<b>설득력 있게(convincingly)</b> 말했다’가 자연스럽다."},
 {"no":118,"text":"To increase overall efficiency, the factory is searching ideas on automating ▢ tasks that were previously done by hand.",
  "opts":["repetition","repetitiveness","repetitive","repetitively"],"ans":2,"type":"품사·형용사","verified":True,
  "expl":"명사 tasks를 수식하는 형용사 <b>repetitive</b>(반복적인)."},
 {"no":119,"text":"Managers have been asked to identify ▢ employees who have most significantly contributed to the project.",
  "opts":["those","theirs","which","where"],"ans":0,"type":"대명사·형용사","verified":True,
  "expl":"‘those + 명사 + who ~(~한 그 직원들)’ 구조 → <b>those</b>."},
 {"no":120,"text":"Clients requesting a full refund must do so ▢ five business days of their initial purchase.",
  "opts":["along","within","from","between"],"ans":1,"type":"전치사","verified":True,
  "expl":"‘구매 후 5영업일 <b>이내에</b>’ → within."},
 {"no":121,"text":"For all matters that must ▢ by the end of the fiscal year, managers should submit their final reports by Friday.",
  "opts":["resolution","to resolve","resolve","be resolved"],"ans":3,"type":"태·형태","verified":True,
  "expl":"‘해결되어야 하는 사안’ → 조동사 must 뒤 수동 <b>be resolved</b>(matters가 해결‘되는’ 대상)."},
 {"no":122,"text":"Healthy Harvest uses ▢ boxes for all takeout orders to reduce waste and support sustainability.",
  "opts":["recyclable","delicious","colorful","rapid"],"ans":0,"type":"어휘·형용사","verified":True,
  "expl":"‘폐기물 감소·지속가능성’ 단서 → ‘<b>재활용 가능한(recyclable)</b>’ 상자.",
  "vocab":[("recyclable","재활용 가능한")]},
 {"no":123,"text":"Last week’s ▢ hot weather led to a record-breaking increase in electricity consumption across the metropolitan area.",
  "opts":["extremity","extremes","extremeness","extremely"],"ans":3,"type":"품사·부사","verified":True,
  "expl":"형용사 hot을 수식하는 부사 <b>extremely</b>(극도로)."},
 {"no":124,"text":"The city council has ▢ a budget for next year that includes $400 million for urban infrastructure.",
  "opts":["controlled","followed","proposed","remained"],"ans":2,"type":"어휘·동사","verified":True,
  "expl":"‘예산을 <b>제안했다(proposed)</b>’. remained는 자동사라 목적어를 못 가진다."},
 {"no":125,"text":"Blue Horizon Tech earned more revenue in January ▢ in the previous three months combined.",
  "opts":["than","additionally","before","wherever"],"ans":0,"type":"비교","verified":True,
  "expl":"비교급 more와 짝을 이루는 <b>than</b>(‘~보다 더 많은 수익’)."},
 {"no":126,"text":"▢ limited resources, the project team successfully finished the construction ahead of time.",
  "opts":["Although","In spite of","Whereas","Due to"],"ans":1,"type":"전치사","verified":True,
  "expl":"뒤에 명사구가 오는 ‘~에도 불구하고’ → <b>In spite of</b>. Although/Whereas는 절이 필요, Due to는 논리가 반대."},
 {"no":127,"text":"Marketing research suggests that the redesigned packaging is more ▢ than the previous version to younger consumers.",
  "opts":["attracts","attractively","attraction","attractive"],"ans":3,"type":"품사·형용사","verified":True,
  "expl":"‘be more <b>attractive</b> than(더 매력적인)’ — be동사 뒤 형용사 비교급."},
 {"no":128,"text":"The committee will ▢ any proposal that does not meet the safety standard set by the government.",
  "opts":["create","arrange","persuade","reject"],"ans":3,"type":"어휘·동사","verified":True,
  "expl":"‘기준 미달 제안을 <b>거부한다(reject)</b>’."},
 {"no":129,"text":"Industry analysts noted that the luxury brand’s prices are ▢ higher than those of other brands.",
  "opts":["significant","significance","significantly","signify"],"ans":2,"type":"품사·부사","verified":True,
  "expl":"비교급 형용사 higher를 수식하는 부사 <b>significantly</b>(상당히)."},
 {"no":130,"text":"The lead architect chose the most ▢ flooring material despite its higher cost to ensure the building’s longevity.",
  "opts":["tilted","durable","saturated","enthusiastic"],"ans":1,"type":"어휘·형용사","verified":True,
  "expl":"‘건물 수명(longevity)’ 단서 → 가장 ‘<b>내구성 있는(durable)</b>’ 자재.",
  "vocab":[("longevity","수명·내구")]},
]

ALL_SETS = [("260228", set228, provided_key_228),
            ("260329", set329, provided_key_329),
            ("260426", set426, provided_key_426)]
