# -*- coding: utf-8 -*-
"""Part 5 (101-130) — 문제는 동일, 해설을 시중 교재 수준으로 상세화(해석·해설·보기분석·어휘)."""

part5 = [
 {"no":101,"text":"The city council approved a substantial ------- in funding for public transportation projects.",
  "opts":["increased","increase","increasingly","increasing"],"ans":1,"type":"품사·명사",
  "trans":"시의회는 대중교통 프로젝트 자금의 상당한 <b>증가</b>를 승인했다.",
  "expl":"관사 a와 형용사 substantial의 수식을 받는 자리이므로 <b>명사</b>가 와야 한다. 명사는 (B) increase(증가)뿐이며, ‘a substantial increase in ~’은 ‘~의 상당한 증가’라는 빈출 표현이다.",
  "opt_why":["과거(분사)형 — 명사 자리에 부적합","명사 ‘증가’ — 정답","부사 — 명사 자리 불가","형용사/동명사 — 관사+형용사 뒤 명사 자리에 부적합"],
  "vocab":[("council","의회"),("substantial","상당한"),("funding","자금·지원금")]},

 {"no":102,"text":"Ms. Alvarado ------- the keynote address at next month's technology summit.",
  "opts":["delivered","delivering","will deliver","has delivered"],"ans":2,"type":"동사·시제",
  "trans":"Alvarado 씨는 다음 달 기술 정상회의에서 기조연설을 <b>할 것이다</b>.",
  "expl":"빈칸은 문장의 동사 자리이며, 미래 시점을 나타내는 <b>next month</b>가 결정적 단서다. 따라서 미래시제 (C) will deliver가 정답이다.",
  "opt_why":["과거 — next month와 시제 충돌","분사 — 본동사가 될 수 없음","미래 — 정답","현재완료 — 미래 표현과 함께 쓸 수 없음"],
  "vocab":[("keynote address","기조연설"),("summit","정상회의·총회")]},

 {"no":103,"text":"All laboratory personnel must wear protective eyewear ------- the entire duration of the experiment.",
  "opts":["among","toward","onto","throughout"],"ans":3,"type":"전치사",
  "trans":"모든 실험실 직원은 실험이 진행되는 <b>내내</b> 보호 안경을 착용해야 한다.",
  "expl":"뒤에 ‘the entire duration(전체 기간)’이라는 기간 명사가 오므로 ‘~ 동안 내내’를 뜻하는 (D) throughout이 정답이다.",
  "opt_why":["‘~ 사이에’(공간) — 부적합","‘~을 향해’ — 부적합","‘~ 위로’ — 부적합","‘~ 내내’ — 정답"],
  "vocab":[("personnel","직원"),("duration","지속 기간"),("protective eyewear","보호 안경")]},

 {"no":104,"text":"Under the new manager, the warehouse fills online orders far more ------- than before.",
  "opts":["accurately","accurate","accuracy","accurateness"],"ans":0,"type":"품사·부사",
  "trans":"새 관리자 아래에서 그 창고는 온라인 주문을 전보다 훨씬 더 <b>정확하게</b> 처리한다.",
  "expl":"동사 fills를 수식하고 ‘far more ~ than’ 비교 구조에 들어가므로 <b>부사</b>가 필요하다. 따라서 (A) accurately가 정답이다.",
  "opt_why":["부사 — 정답","형용사 — 동사 수식 불가","명사","명사"],
  "vocab":[("warehouse","창고"),("fill an order","주문을 처리하다")]},

 {"no":105,"text":"The architect ------- designed the award-winning museum will lead the new library project.",
  "opts":["whom","whose","who","which"],"ans":2,"type":"관계대명사",
  "trans":"그 수상 경력의 박물관을 설계한 건축가가 새 도서관 프로젝트를 이끌 것이다.",
  "expl":"빈칸 뒤 designed의 주어가 없으므로 <b>주격 관계대명사</b>가 필요하고, 선행사가 사람(the architect)이므로 (C) who가 정답이다.",
  "opt_why":["목적격 — 주어 자리 불가","소유격 — 뒤에 명사 필요","주격(사람) — 정답","사물용 — 부적합"],
  "vocab":[("architect","건축가"),("award-winning","수상 경력의")]},

 {"no":106,"text":"------- its limited marketing budget, the startup attracted thousands of new subscribers.",
  "opts":["Although","Despite","Even though","Whereas"],"ans":1,"type":"전치사 vs 접속사",
  "trans":"제한된 마케팅 예산에도 <b>불구하고</b>, 그 스타트업은 수천 명의 신규 구독자를 끌어모았다.",
  "expl":"빈칸 뒤에 <b>명사구</b>(its limited marketing budget)가 오므로 전치사인 (B) Despite가 정답이다. 나머지는 모두 접속사여서 뒤에 ‘주어+동사’ 절이 와야 한다.",
  "opt_why":["접속사 — 절 필요","전치사(+명사구) ‘~에도 불구하고’ — 정답","접속사 — 절 필요","접속사 ‘~인 반면’ — 절 필요"],
  "vocab":[("limited","제한된"),("subscriber","구독자")]},

 {"no":107,"text":"The finance department will ------- all travel expenses within ten business days of submission.",
  "opts":["remind","recover","refer","reimburse"],"ans":3,"type":"어휘·동사",
  "trans":"재무부는 제출 후 10영업일 이내에 모든 출장 경비를 <b>환급할</b> 것이다.",
  "expl":"목적어 ‘travel expenses(출장 경비)’와 어울려 ‘(비용을) 환급하다’를 뜻하는 (D) reimburse가 정답이다.",
  "opt_why":["‘상기시키다’(사람을 목적어로)","‘회복하다·되찾다’","‘언급하다’(refer to)","‘환급하다’ — 정답"],
  "vocab":[("reimburse","환급하다"),("expense","경비"),("submission","제출")]},

 {"no":108,"text":"The board found the consultant's recommendations both practical and -------.",
  "opts":["persuasive","persuade","persuasively","persuasion"],"ans":0,"type":"품사·형용사",
  "trans":"이사회는 그 컨설턴트의 권고가 실용적이면서 <b>설득력도 있다고</b> 여겼다.",
  "expl":"‘both A and B’ 구조에서 A가 형용사 practical이므로 B도 <b>형용사</b>여야 한다. 따라서 (A) persuasive가 정답이다. (find + 목적어 + 형용사 보어)",
  "opt_why":["형용사 — 정답","동사","부사","명사"],
  "vocab":[("board","이사회"),("practical","실용적인"),("persuasive","설득력 있는")]},

 {"no":109,"text":"The new safety regulations ------- by the committee before they take effect in January.",
  "opts":["will review","reviewing","will be reviewed","have reviewing"],"ans":2,"type":"동사·태",
  "trans":"새 안전 규정은 1월에 시행되기 전에 위원회에 의해 <b>검토될 것이다</b>.",
  "expl":"주어 regulations는 검토를 ‘받는’ 대상이고 행위자 ‘by the committee’가 있으므로 <b>수동태</b>가 필요하다. 미래 수동태 (C) will be reviewed가 정답이다.",
  "opt_why":["능동 — 규정이 검토 주체가 되어 부적합","분사 — 본동사 불가","미래 수동 — 정답","문법상 성립하지 않음"],
  "vocab":[("regulation","규정"),("take effect","발효되다"),("committee","위원회")]},

 {"no":110,"text":"------- of the applicants has submitted the required documentation by the deadline.",
  "opts":["All","Many","Several","Each"],"ans":3,"type":"수일치·수량",
  "trans":"지원자들 <b>각각은</b> 마감 기한까지 필요한 서류를 제출했다.",
  "expl":"동사가 <b>단수(has submitted)</b>이므로 단수 취급하는 (D) Each가 정답이다. ‘Each of the + 복수명사’는 단수 동사를 받는다. 나머지는 복수 취급하여 동사가 have여야 한다.",
  "opt_why":["복수 취급 — have 필요","복수 취급 — have 필요","복수 취급 — have 필요","단수 취급 — 정답"],
  "vocab":[("applicant","지원자"),("documentation","서류"),("deadline","마감 기한")]},

 {"no":111,"text":"Please submit your quarterly report ------- Friday so that we can review it over the weekend.",
  "opts":["until","by","since","within"],"ans":1,"type":"전치사·시간",
  "trans":"주말에 검토할 수 있도록 분기 보고서를 금요일<b>까지</b> 제출해 주세요.",
  "expl":"submit(제출)은 한 번에 ‘완료되는’ 동작이므로 완료 기한을 뜻하는 (B) by가 정답이다. until은 상태·동작의 ‘계속’에 쓰여 submit과 맞지 않는다.",
  "opt_why":["‘~까지 계속’ — 완료 동작 submit과 부적합","‘~까지(완료)’ — 정답","‘~ 이래로’","‘~ 이내에’(+기간 명사)"],
  "vocab":[("quarterly","분기의"),("submit","제출하다")]},

 {"no":112,"text":"The merger will require the ------- of several regional offices into a single headquarters.",
  "opts":["consolidate","consolidated","consolidation","consolidates"],"ans":2,"type":"품사·명사",
  "trans":"그 합병은 여러 지역 사무소를 하나의 본사로 <b>통합</b>하는 것을 필요로 할 것이다.",
  "expl":"관사 the 뒤이자 require의 목적어 자리이므로 <b>명사</b> (C) consolidation(통합)이 정답이다.",
  "opt_why":["동사","과거분사","명사 — 정답","동사(3인칭 단수)"],
  "vocab":[("merger","합병"),("consolidation","통합"),("headquarters","본사")]},

 {"no":113,"text":"The assembly instructions were so ------- that even new employees completed the setup without assistance.",
  "opts":["straightforward","reluctant","tentative","approximate"],"ans":0,"type":"어휘·형용사",
  "trans":"조립 설명서가 매우 <b>이해하기 쉬워서</b> 신입 직원조차 도움 없이 설치를 마쳤다.",
  "expl":"‘so + 형용사 + that(너무 ~해서 …하다)’ 구문. 신입도 도움 없이 마쳤다는 결과와 어울리는 ‘이해하기 쉬운’ (A) straightforward가 정답이다.",
  "opt_why":["‘이해하기 쉬운·간단명료한’ — 정답","‘꺼리는’","‘잠정적인’","‘대략적인’"],
  "vocab":[("assembly","조립"),("straightforward","이해하기 쉬운"),("assistance","도움")]},

 {"no":114,"text":"Customers visiting the newly ------- store received a complimentary gift on opening day.",
  "opts":["renovate","renovating","renovation","renovated"],"ans":3,"type":"품사·분사",
  "trans":"새로 <b>개조된</b> 매장을 방문한 고객들은 개점일에 무료 선물을 받았다.",
  "expl":"명사 store를 앞에서 수식하며 ‘개조된(수동)’ 의미를 나타내야 하므로 <b>과거분사</b> (D) renovated가 정답이다. 부사 newly의 수식을 받는다.",
  "opt_why":["동사","현재분사 ‘개조하는’(능동)","명사","과거분사 ‘개조된’ — 정답"],
  "vocab":[("complimentary","무료의"),("renovate","개조하다")]},

 {"no":115,"text":"The shipment will be delayed ------- the supplier resolves the issue with its manufacturing line.",
  "opts":["during","until","despite","because of"],"ans":1,"type":"접속사",
  "trans":"그 배송은 공급업체가 생산 라인 문제를 해결할 <b>때까지</b> 지연될 것이다.",
  "expl":"빈칸 뒤에 ‘주어(the supplier)+동사(resolves)’ 절이 오므로 <b>접속사</b>가 필요하고, ‘~할 때까지’를 뜻하는 (B) until이 정답이다. 나머지는 전치사(구)라 뒤에 명사가 와야 한다.",
  "opt_why":["전치사 — 명사 필요","접속사 ‘~할 때까지’ — 정답","전치사 — 명사 필요","전치사구 — 명사 필요"],
  "vocab":[("shipment","배송(품)"),("supplier","공급업체"),("resolve","해결하다")]},

 {"no":116,"text":"The airline advised passengers to ------- their flight status online before heading to the airport.",
  "opts":["persist","belong","confirm","consent"],"ans":2,"type":"어휘·동사",
  "trans":"그 항공사는 승객들에게 공항으로 출발하기 전에 온라인으로 항공편 상태를 <b>확인하라고</b> 권했다.",
  "expl":"목적어 ‘flight status(항공편 상태)’와 어울려 ‘확인하다’를 뜻하는 (C) confirm이 정답이다. 나머지는 자동사이거나 의미가 맞지 않는다.",
  "opt_why":["‘지속되다’(자동사)","‘속하다’(belong to)","‘확인하다’ — 정답","‘동의하다’(consent to)"],
  "vocab":[("advise","권하다"),("flight status","항공편 운항 상태")]},

 {"no":117,"text":"The organization has ------- expanded its outreach programs over the past five years.",
  "opts":["significantly","signify","significant","significance"],"ans":0,"type":"품사·부사",
  "trans":"그 단체는 지난 5년에 걸쳐 봉사 프로그램을 <b>상당히</b> 확대해 왔다.",
  "expl":"‘has ------- expanded’에서 조동사와 과거분사 사이의 동사를 수식하는 <b>부사</b> 자리이므로 (A) significantly(상당히)가 정답이다.",
  "opt_why":["부사 — 정답","동사","형용사","명사"],
  "vocab":[("outreach","(지역) 봉사 활동"),("expand","확대하다")]},

 {"no":118,"text":"After the training session, employees are encouraged to familiarize ------- with the updated procedures.",
  "opts":["they","them","their","themselves"],"ans":3,"type":"대명사·재귀",
  "trans":"교육 후, 직원들은 갱신된 절차에 <b>스스로</b> 익숙해지도록 권장된다.",
  "expl":"‘familiarize oneself with(~에 익숙해지다)’ 관용 구조이며, 목적어가 주어(employees)와 같으므로 <b>재귀대명사</b> (D) themselves가 정답이다.",
  "opt_why":["주격","목적격(주어와 다른 대상)","소유격","재귀대명사 — 정답"],
  "vocab":[("familiarize oneself with","~에 익숙해지다"),("procedure","절차")]},

 {"no":119,"text":"The consultant's fee is determined ------- the complexity of each project.",
  "opts":["according","by","into","among"],"ans":1,"type":"전치사",
  "trans":"그 컨설턴트의 수수료는 각 프로젝트의 복잡성에 <b>따라</b> 결정된다.",
  "expl":"‘be determined by(~에 의해 결정되다)’의 짝 표현으로 (B) by가 정답이다. according은 반드시 to와 함께 써야 하고, into·among은 의미가 맞지 않는다.",
  "opt_why":["‘according to’로 써야 함","‘~에 의해’ — 정답","‘~ 안으로’","‘~ 사이에’"],
  "vocab":[("fee","수수료"),("complexity","복잡성"),("determine","결정하다")]},

 {"no":120,"text":"The new policy was implemented in ------- to growing concerns about data privacy.",
  "opts":["contrast","exchange","response","addition"],"ans":2,"type":"어휘·관용",
  "trans":"그 새 정책은 데이터 프라이버시에 대한 커지는 우려에 <b>대응하여</b> 시행되었다.",
  "expl":"‘in response to(~에 대응하여)’라는 관용 표현으로 (C) response가 정답이다.",
  "opt_why":["in contrast to ‘~와 대조적으로’","in exchange for ‘~ 대신’","in response to ‘~에 대응하여’ — 정답","in addition to ‘~에 더하여’"],
  "vocab":[("implement","시행하다"),("concern","우려"),("privacy","사생활·개인정보")]},

 {"no":121,"text":"To remain competitive, the firm must ------- its production process and reduce costs.",
  "opts":["streamline","streamlined","streamlining","streamlines"],"ans":0,"type":"동사·형태",
  "trans":"경쟁력을 유지하기 위해, 그 회사는 생산 공정을 <b>간소화하고</b> 비용을 절감해야 한다.",
  "expl":"조동사 must 뒤에는 항상 <b>동사원형</b>이 오므로 (A) streamline(간소화하다)이 정답이다. 뒤의 reduce와 병렬을 이루는 원형이다.",
  "opt_why":["동사원형 — 정답","과거(분사)","분사·동명사","3인칭 단수형"],
  "vocab":[("streamline","간소화하다"),("competitive","경쟁력 있는"),("reduce","절감하다")]},

 {"no":122,"text":"Of all the proposals submitted, the one from the Denver office was by far the -------.",
  "opts":["detailed","more detailed","detailing","most detailed"],"ans":3,"type":"비교·최상급",
  "trans":"제출된 모든 제안서 중에서 덴버 사무소의 것이 <b>단연 가장 상세했다</b>.",
  "expl":"‘Of all(모든 것 중에서)’과 정관사+‘by far(단연)’은 <b>최상급</b>과 함께 쓰이므로 (D) most detailed가 정답이다.",
  "opt_why":["원급","비교급(둘 비교)","분사","최상급 — 정답"],
  "vocab":[("proposal","제안서"),("by far","단연"),("detailed","상세한")]},

 {"no":123,"text":"The venue is easily ------- by public transportation, making it ideal for large conferences.",
  "opts":["available","accessible","probable","eligible"],"ans":1,"type":"어휘·형용사",
  "trans":"그 장소는 대중교통으로 쉽게 <b>접근할 수 있어</b> 대규모 회의에 이상적이다.",
  "expl":"‘by public transportation(대중교통으로)’과 어울려 ‘접근 가능한’을 뜻하는 (B) accessible이 정답이다.",
  "opt_why":["‘이용 가능한’(교통수단과 어색)","‘접근 가능한’(accessible by) — 정답","‘있음직한’","‘자격 있는’(eligible for)"],
  "vocab":[("venue","(행사) 장소"),("accessible","접근 가능한"),("ideal","이상적인")]},

 {"no":124,"text":"The research team collaborated ------- several universities to complete the climate study.",
  "opts":["among","between","with","toward"],"ans":2,"type":"전치사",
  "trans":"그 연구팀은 기후 연구를 완료하기 위해 여러 대학과 <b>협력했다</b>.",
  "expl":"‘collaborate with(~와 협력하다)’의 짝 표현으로 (C) with가 정답이다.",
  "opt_why":["‘~ 사이에’","‘(둘) 사이에’","‘~와 함께’ — 정답","‘~을 향해’"],
  "vocab":[("collaborate with","~와 협력하다"),("climate","기후")]},

 {"no":125,"text":"All ------- for the workshop must be submitted to the human resources department by Friday.",
  "opts":["registrations","register","registered","registering"],"ans":0,"type":"품사·명사",
  "trans":"워크숍 <b>참가 신청서</b>는 모두 금요일까지 인사부에 제출되어야 한다.",
  "expl":"수량 형용사 All의 수식을 받고 동사 ‘must be submitted’의 주어가 되는 <b>명사</b> 자리이므로 (A) registrations(신청서)가 정답이다. ‘All + 복수명사’ 형태다.",
  "opt_why":["명사(복수) — 정답","동사","과거분사","분사·동명사"],
  "vocab":[("registration","신청·등록"),("human resources","인사부")]},

 {"no":126,"text":"The renovated lobby features not only a modern reception desk ------- also a comfortable waiting area.",
  "opts":["and","or","nor","but"],"ans":3,"type":"상관접속사",
  "trans":"개조된 로비는 현대적인 안내 데스크<b>뿐만 아니라</b> 편안한 대기 공간도 갖추고 있다.",
  "expl":"‘not only A but also B(A뿐만 아니라 B도)’의 상관접속사 구조이므로 (D) but이 정답이다.",
  "opt_why":["‘not only’와 짝 아님","‘not only’와 짝 아님","‘not only’와 짝 아님","‘not only ~ but also’ — 정답"],
  "vocab":[("feature","~을 특징으로 갖추다"),("reception desk","안내 데스크")]},

 {"no":127,"text":"Sales representatives are expected to ------- closely to the company's code of conduct at all times.",
  "opts":["respond","adhere","belong","refer"],"ans":1,"type":"어휘·동사",
  "trans":"영업 담당자들은 항상 회사의 행동 강령을 철저히 <b>준수할</b> 것으로 기대된다.",
  "expl":"전치사 to 및 ‘code of conduct(행동 강령)’와 어울려 ‘준수하다’를 뜻하는 (B) adhere(to)가 정답이다.",
  "opt_why":["‘반응하다’(respond to)","‘준수하다’(adhere to) — 정답","‘속하다’(belong to)","‘언급하다’(refer to)"],
  "vocab":[("adhere to","준수하다"),("code of conduct","행동 강령"),("representative","담당자")]},

 {"no":128,"text":"The committee described the volunteers' efforts as truly ------- and worthy of recognition.",
  "opts":["inspire","inspired","inspiring","inspiration"],"ans":2,"type":"품사·분사",
  "trans":"위원회는 자원봉사자들의 노력이 참으로 <b>감동적이고</b> 인정받을 만하다고 평했다.",
  "expl":"‘efforts(노력)’가 감동을 ‘주는’ 능동 의미이므로 <b>현재분사</b> (C) inspiring(감동적인)이 정답이다. 과거분사 inspired는 감정을 ‘느끼는’ 사람에게 쓴다. 형용사 worthy와 병렬된다.",
  "opt_why":["동사","과거분사 ‘감동받은’(사람에)","현재분사 ‘감동적인’ — 정답","명사"],
  "vocab":[("worthy of","~할 만한"),("recognition","인정"),("inspiring","감동적인")]},

 {"no":129,"text":"The keynote speaker's flight was delayed, so the organizers rearranged the schedule -------.",
  "opts":["accordingly","accordance","accordant","according"],"ans":0,"type":"품사·부사",
  "trans":"기조 연사의 항공편이 지연되어, 주최 측은 <b>그에 따라</b> 일정을 재조정했다.",
  "expl":"동사 rearranged를 뒤에서 수식하는 <b>부사</b> 자리이므로 (A) accordingly(그에 따라)가 정답이다. accordance는 명사(in accordance with), according은 according to로만 쓴다.",
  "opt_why":["부사 ‘그에 따라’ — 정답","명사(in accordance with)","형용사","‘according to’로 써야 함"],
  "vocab":[("rearrange","재조정하다"),("keynote speaker","기조 연사")]},

 {"no":130,"text":"The manufacturer offers a ------- warranty that covers all parts and labor for three years.",
  "opts":["considerate","confident","conscious","comprehensive"],"ans":3,"type":"어휘·형용사",
  "trans":"그 제조사는 3년간 모든 부품과 인건비를 보장하는 <b>포괄적인</b> 보증을 제공한다.",
  "expl":"부품과 인건비를 ‘모두’ 보장한다는 내용과 어울려 ‘포괄적인’을 뜻하는 (D) comprehensive가 정답이다. 나머지는 사람의 성향을 나타내 사물 warranty와 맞지 않는다.",
  "opt_why":["‘사려 깊은’","‘자신 있는’","‘의식하는’","‘포괄적인’ — 정답"],
  "vocab":[("manufacturer","제조사"),("warranty","보증"),("comprehensive","포괄적인"),("labor","인건비")]},
]
