# -*- coding: utf-8 -*-
"""Part 5 — Incomplete Sentences (Q101-130)"""

part5 = [
    {"no":101,
     "text":"Because of her extensive ------- in international trade, Ms. Reyes was promoted to regional director.",
     "opts":["experience","experienced","experiences","experiencing"],"ans":0,"type":"품사·명사",
     "expl":"소유격 her와 형용사 extensive의 수식을 받는 <b>명사</b> 자리다. experience는 ‘경력·경험’의 의미일 때 불가산명사로 쓰여 <b>experience</b>가 정답. experiences(가산·개별 경험)는 extensive와 어울리지 않는다.",
     "vocab":[("extensive","폭넓은"),("international trade","국제 무역"),("regional director","지역 이사")]},

    {"no":102,
     "text":"All visitors must sign in at the front desk ------- entering the research laboratory.",
     "opts":["while","during","before","since"],"ans":2,"type":"전치사·시간",
     "expl":"‘실험실에 들어가기 <b>전에</b> 방문록에 서명해야 한다’는 순서이므로 <b>before</b>가 정답. before는 뒤에 동명사(entering)를 취할 수 있다.",
     "opt_why":["‘~하는 동안’이라 순서 논리에 안 맞음","during 뒤엔 명사만 옴(+동명사 불가)","‘~하기 전에’ — 정답","‘~한 이래로’로 문맥에 안 맞음"],
     "vocab":[("sign in","서명하고 입장하다"),("laboratory","실험실")]},

    {"no":103,
     "text":"By the time the shipment arrives, the warehouse staff ------- additional storage space.",
     "opts":["prepared","has prepared","preparing","will have prepared"],"ans":3,"type":"동사·시제",
     "expl":"‘By the time + 현재시제(arrives)’가 미래의 시점을 나타내면 주절은 그 시점까지 완료를 뜻하는 <b>미래완료(will have prepared)</b>를 쓴다.",
     "vocab":[("shipment","배송(물)"),("warehouse","창고"),("storage space","보관 공간")]},

    {"no":104,
     "text":"The new accounting software processes invoices far more ------- than the previous system did.",
     "opts":["efficient","efficiently","efficiency","efficiencies"],"ans":1,"type":"품사·부사",
     "expl":"동사 processes를 수식하는 <b>부사</b> 자리이며, ‘far more ------- than’ 비교급 구조 안에서도 부사가 필요하다. 따라서 <b>efficiently</b>.",
     "vocab":[("invoice","송장·청구서"),("previous","이전의")]},

    {"no":105,
     "text":"The senior managers reviewed the merger proposals ------- before presenting them to the client.",
     "opts":["they","their","themselves","them"],"ans":2,"type":"대명사·재귀",
     "expl":"주어(The senior managers)가 직접 검토했음을 강조하는 <b>재귀대명사 themselves</b>(‘직접’)가 정답. 문장 성분이 이미 완전하므로 강조 용법이다.",
     "vocab":[("merger","합병"),("proposal","제안(서)")]},

    {"no":106,
     "text":"The conference room on the third floor is reserved ------- the marketing department every Monday.",
     "opts":["for","to","with","of"],"ans":0,"type":"전치사·짝",
     "expl":"‘be reserved <b>for</b> ~’(~을 위해 예약되다)의 짝 표현. reserve A for B 구조를 수동으로 쓴 형태다.",
     "vocab":[("reserve","예약하다"),("department","부서")]},

    {"no":107,
     "text":"------- the heavy rain, the outdoor product launch proceeded exactly as scheduled.",
     "opts":["Although","Despite","Because","However"],"ans":1,"type":"전치사 vs 접속사",
     "expl":"빈칸 뒤에 <b>명사구(the heavy rain)</b>가 오므로 전치사 <b>Despite</b>(~에도 불구하고)가 정답. Although·Because는 접속사여서 뒤에 ‘절’이 필요하고, However는 접속부사다.",
     "opt_why":["접속사 — 뒤에 절이 와야 함","전치사(+명사구) ‘~에도 불구하고’ — 정답","접속사(이유) — 절 필요","접속부사 — 문장 연결부사"],
     "vocab":[("product launch","제품 출시"),("proceed","진행되다"),("as scheduled","예정대로")]},

    {"no":108,
     "text":"The renovation was completed in a ------- manner, well within the allotted budget.",
     "opts":["time","timing","times","timely"],"ans":3,"type":"품사·형용사",
     "expl":"관사 a와 명사 manner 사이의 <b>형용사</b> 자리. timely는 -ly로 끝나지만 ‘시기적절한’이라는 <b>형용사</b>다. ‘in a timely manner’=적시에.",
     "vocab":[("renovation","보수·개조"),("allotted","할당된"),("budget","예산")]},

    {"no":109,
     "text":"The updated safety guidelines ------- to all staff members during last week's orientation.",
     "opts":["distributed","were distributed","have distributing","distributing"],"ans":1,"type":"동사·태",
     "expl":"지침(guidelines)은 ‘배포되는’ 대상이므로 <b>수동태</b>가 필요하고, last week이 과거이므로 <b>were distributed</b>가 정답.",
     "vocab":[("guidelines","지침"),("distribute","배포하다")]},

    {"no":110,
     "text":"The technician was able to ------- the software malfunction within an hour of arriving on-site.",
     "opts":["resolve","apply","remain","consist"],"ans":0,"type":"어휘·동사",
     "expl":"목적어 malfunction(오작동)과 어울려 ‘해결하다’를 뜻하는 <b>resolve</b>가 정답.",
     "opt_why":["‘(문제를) 해결하다’ — 정답","‘적용하다’, 목적어와 안 맞음","‘남아 있다’(자동사)","‘구성되다’(consist of)"],
     "vocab":[("malfunction","오작동"),("on-site","현장에서")]},

    {"no":111,
     "text":"Ms. Alvarez, ------- has led the design team for five years, will oversee the rebranding.",
     "opts":["whom","whose","who","which"],"ans":2,"type":"관계대명사",
     "expl":"사람 선행사(Ms. Alvarez)를 받으면서 관계절의 <b>주어</b> 역할을 하므로 주격 관계대명사 <b>who</b>가 정답. whom(목적격)·whose(소유격)·which(사물)는 부적절.",
     "vocab":[("oversee","감독하다"),("rebranding","브랜드 개편")]},

    {"no":112,
     "text":"Of the three finalists, Mr. Okafor presented the ------- qualifications for the position.",
     "opts":["strong","stronger","strongly","strongest"],"ans":3,"type":"비교·최상급",
     "expl":"‘Of the three(셋 중에서)’와 정관사 the가 있으므로 <b>최상급 strongest</b>가 정답. 셋 이상 비교에는 최상급을 쓴다.",
     "vocab":[("finalist","최종 후보"),("qualification","자격 요건")]},

    {"no":113,
     "text":"------- to the downtown office has become far easier since the new subway line opened.",
     "opts":["Commute","Commuting","Commuted","Commutes"],"ans":1,"type":"품사·동명사 주어",
     "expl":"관사 없이 문장의 <b>주어</b> 자리이면서 뒤에 ‘to the downtown office’를 이끄는 <b>동명사 Commuting</b>이 정답. 명사 Commute를 쓰려면 관사가 필요하다.",
     "vocab":[("commute","통근(하다)"),("subway line","지하철 노선")]},

    {"no":114,
     "text":"Please place your completed evaluation forms ------- the box located near the main entrance.",
     "opts":["in","onto","among","between"],"ans":0,"type":"전치사·장소",
     "expl":"‘상자 <b>안에</b> 넣다’라는 의미이므로 <b>in</b>이 정답. among(셋 이상 사이)·between(둘 사이)은 문맥에 안 맞는다.",
     "vocab":[("evaluation form","평가서"),("entrance","입구")]},

    {"no":115,
     "text":"------- you have any questions regarding the invoice, please contact our billing department.",
     "opts":["Were","Had","Would","Should"],"ans":3,"type":"가정법 도치",
     "expl":"‘If you should have ~’의 if가 생략되며 조동사가 앞으로 나온 <b>도치 구문</b>. 따라서 <b>Should</b>가 정답이며 ‘혹시 ~라면’의 뜻이다.",
     "vocab":[("regarding","~에 관하여"),("billing department","청구 부서")]},

    {"no":116,
     "text":"The initial proposal received ------- feedback from the review board, prompting several revisions.",
     "opts":["capable","willing","critical","eligible"],"ans":2,"type":"어휘·형용사",
     "expl":"수정(revisions)을 촉발했다는 맥락상 ‘비판적인’ 피드백이 자연스러우므로 <b>critical</b>이 정답.",
     "opt_why":["‘유능한’(사람 수식)","‘기꺼이 하는’(be willing to)","‘비판적인’ — 정답","‘자격이 있는’(be eligible for)"],
     "vocab":[("review board","심사 위원회"),("prompt","촉발하다"),("revision","수정")]},

    {"no":117,
     "text":"Second-quarter sales were ------- higher than the analysts had originally predicted.",
     "opts":["significant","significantly","significance","signify"],"ans":1,"type":"품사·부사",
     "expl":"비교급 형용사 higher를 수식하는 <b>부사</b> 자리이므로 <b>significantly</b>(상당히)가 정답.",
     "vocab":[("analyst","분석가"),("predict","예측하다")]},

    {"no":118,
     "text":"Neither the department supervisor nor the assistants ------- aware of the last-minute schedule change.",
     "opts":["was","is","has been","were"],"ans":3,"type":"수일치",
     "expl":"‘Neither A nor B’ 구조에서 동사는 <b>가까운 주어 B(the assistants, 복수)</b>에 일치시킨다. 과거 문맥이므로 <b>were</b>가 정답.",
     "vocab":[("supervisor","관리자"),("aware of","~을 알고 있는"),("last-minute","막판의")]},

    {"no":119,
     "text":"Over the past decade, the firm has expanded its operations ------- three continents.",
     "opts":["across","along","toward","into"],"ans":0,"type":"전치사",
     "expl":"‘세 대륙에 <b>걸쳐</b> 사업을 확장했다’는 의미이므로 <b>across</b>가 정답.",
     "vocab":[("expand","확장하다"),("operations","사업·운영"),("continent","대륙")]},

    {"no":120,
     "text":"Staff are encouraged to take ------- of the professional development courses offered each spring.",
     "opts":["benefit","profit","advantage","favor"],"ans":2,"type":"어휘·관용구",
     "expl":"‘take <b>advantage</b> of ~’(~을 이용하다)라는 관용 표현. 다른 명사들은 이 구조에 쓰지 않는다.",
     "opt_why":["‘이익’, 관용구 아님","‘수익’","take advantage of ‘~을 활용하다’ — 정답","‘호의’, in favor of로 쓰임"],
     "vocab":[("professional development","직무 능력 개발"),("encourage","권장하다")]},

    {"no":121,
     "text":"Passengers holding ------- reservations should proceed directly to the priority boarding lane.",
     "opts":["confirm","confirms","confirming","confirmed"],"ans":3,"type":"품사·분사",
     "expl":"명사 reservations를 수식하며 ‘확정된’이라는 <b>수동의 의미</b>를 나타내므로 과거분사 <b>confirmed</b>가 정답.",
     "vocab":[("reservation","예약"),("proceed","이동하다"),("boarding lane","탑승 통로")]},

    {"no":122,
     "text":"The agency hired two additional translators ------- meet the growing demand for its services.",
     "opts":["to","for","so","in order"],"ans":0,"type":"부정사·목적",
     "expl":"‘~하기 위해’라는 목적을 나타내는 <b>to부정사</b>가 정답. in order는 ‘in order to’, so는 ‘so as to/so that’ 형태여야 한다.",
     "vocab":[("translator","번역가"),("demand","수요")]},

    {"no":123,
     "text":"The revised procedure is intended to ------- communication between the sales and production teams.",
     "opts":["commute","streamline","reside","proceed"],"ans":1,"type":"어휘·동사",
     "expl":"목적어 communication과 어울려 ‘(과정을) 간소화·능률화하다’를 뜻하는 <b>streamline</b>이 정답.",
     "opt_why":["‘통근하다’","‘간소화하다’ — 정답","‘거주하다’(reside in)","‘진행되다’(자동사)"],
     "vocab":[("revised","개정된"),("procedure","절차"),("streamline","간소화하다")]},

    {"no":124,
     "text":"The committee expressed its ------- with the vendor's prompt handling of the complaint.",
     "opts":["satisfy","satisfied","satisfactory","satisfaction"],"ans":3,"type":"품사·명사",
     "expl":"소유격 its 뒤 <b>명사</b> 자리이므로 <b>satisfaction</b>이 정답. ‘express satisfaction with ~’(~에 만족을 표하다).",
     "vocab":[("vendor","공급업체"),("prompt","신속한"),("complaint","불만·항의")]},

    {"no":125,
     "text":"The training program is designed ------- for new hires and for experienced staff updating their skills.",
     "opts":["both","either","neither","not only"],"ans":0,"type":"상관접속사",
     "expl":"‘for A and for B’ 구조와 짝을 이루어 ‘A와 B 둘 다’를 뜻하는 <b>both ... and ...</b>가 정답. either는 or, neither는 nor, not only는 but also와 짝을 이룬다.",
     "vocab":[("new hire","신입 사원"),("experienced","숙련된")]},

    {"no":126,
     "text":"------- request, the finance office will provide a detailed breakdown of all service charges.",
     "opts":["Into","Beside","Upon","Except"],"ans":2,"type":"전치사·관용",
     "expl":"‘<b>Upon</b> request’(요청 시)라는 관용 표현. ‘~하자마자, ~할 때’를 뜻한다.",
     "vocab":[("breakdown","(항목별) 명세"),("service charge","수수료")]},

    {"no":127,
     "text":"Since its founding in 2010, the nonprofit ------- more than fifty community revitalization projects.",
     "opts":["funds","funded","has funded","will fund"],"ans":2,"type":"동사·시제",
     "expl":"‘Since + 과거 시점’은 현재완료와 함께 쓰이므로 <b>has funded</b>가 정답. ‘창립 이래 지금까지 자금을 지원해 왔다’.",
     "vocab":[("nonprofit","비영리 단체"),("fund","자금을 대다"),("revitalization","활성화")]},

    {"no":128,
     "text":"The assembly instructions were so ------- that even first-time users finished the setup quickly.",
     "opts":["aware","clear","eager","willing"],"ans":1,"type":"어휘·형용사",
     "expl":"‘so + 형용사 + that’ 구문에서, 초보자도 빨리 끝냈다는 결과와 어울리는 ‘명확한’ <b>clear</b>가 정답.",
     "opt_why":["‘알고 있는’(be aware of)","‘명확한’ — 정답","‘열망하는’(be eager to)","‘기꺼이 하는’(be willing to)"],
     "vocab":[("assembly","조립"),("setup","설치·조립")]},

    {"no":129,
     "text":"Customers found the redesigned mobile app far more ------- than the earlier version.",
     "opts":["appeal","appealed","appeals","appealing"],"ans":3,"type":"품사·분사",
     "expl":"사물(app)이 매력을 ‘주는’ 능동 의미이므로 현재분사 <b>appealing</b>(매력적인)이 정답. 과거분사 appealed는 감정을 ‘느끼는’ 대상에 쓴다.",
     "vocab":[("redesigned","새로 디자인된"),("appealing","매력적인")]},

    {"no":130,
     "text":"The manufacturer is fully ------- with all national product-safety regulations.",
     "opts":["compliant","responsible","dependent","familiar"],"ans":0,"type":"어휘·형용사",
     "expl":"전치사 with, 그리고 regulations(규정)와 어울려 ‘~을 준수하는’을 뜻하는 <b>compliant</b>가 정답. ‘be compliant with ~’.",
     "opt_why":["‘준수하는’(be compliant with) — 정답","‘책임 있는’은 for와 결합","‘의존하는’은 on과 결합","‘익숙한’은 문맥상 부적절"],
     "vocab":[("manufacturer","제조업체"),("regulation","규정"),("compliant","준수하는")]},
]
